In [1]:
import sys
import os
sys.path.append(os.path.abspath("../.."))

from app.data_providers import test_train_dataset
from processing.compute_columns import add_shot_main_action_type_column

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import TargetEncoder
from sklearn.preprocessing import FunctionTransformer

from sklearn.calibration import CalibrationDisplay

from sklearn.pipeline import FeatureUnion
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer, make_column_transformer

from sklearn.metrics import roc_auc_score, f1_score
from sklearn.metrics import classification_report

from imblearn.over_sampling import RandomOverSampler

from xgboost import XGBClassifier

import joblib

from copy import deepcopy

import shap

pd.set_option('display.max_columns', None)

In [2]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score,
    log_loss,
    brier_score_loss
)

import tensorflow as tf
from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout,
    BatchNormalization,
    Embedding,
    Flatten,
    Concatenate
)
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

# Data preparation

In [3]:
data_train = pd.read_parquet(r"../../data/trajectory_tests/train_new_all_players_v3.parquet")
data_train.set_index('Unnamed: 0', inplace=True)
data_train = data_train.rename_axis(index=None, axis=1)

data_test = pd.read_parquet(r"../../data/trajectory_tests/test_new_all_players_v3.parquet")
data_test.set_index('Unnamed: 0', inplace=True)
data_test = data_test.rename_axis(index=None, axis=1)

In [4]:
data_train.head()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,shooter_speed,player1_speed,player2_speed,player3_speed,player4_speed,player5_speed,player6_speed,player7_speed,player8_speed,player9_speed,player10_speed,defender_closing_speed,ball_height,ball_speed,ball_xy_speed,ACTION_TYPE,EVENTTIME,EVENT_TYPE,GAME_DATE,GAME_EVENT_ID,GAME_ID,GRID_TYPE,HTM,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,SHOT_TYPE,SHOT_ZONE_AREA,SHOT_ZONE_BASIC,SHOT_ZONE_RANGE,TEAM_ID,TEAM_NAME,VTM,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_WCTIMESTRING,event_PCTIMESTRING,event_HOMEDESCRIPTION,event_NEUTRALDESCRIPTION,event_VISITORDESCRIPTION,event_SCORE,event_SCOREMARGIN,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_NAME,event_PLAYER1_TEAM_ID,event_PLAYER1_TEAM_CITY,event_PLAYER1_TEAM_NICKNAME,event_PLAYER1_TEAM_ABBREVIATION,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_NAME,event_PLAYER2_TEAM_ID,event_PLAYER2_TEAM_CITY,event_PLAYER2_TEAM_NICKNAME,event_PLAYER2_TEAM_ABBREVIATION,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_NAME,event_PLAYER3_TEAM_ID,event_PLAYER3_TEAM_CITY,event_PLAYER3_TEAM_NICKNAME,event_PLAYER3_TEAM_ABBREVIATION,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,nearest_teammate_distance,defenders_between,has_screen,offensive_spacing,teammate_between_defender,players_in_paint,match_key
20518,3.0,87.51795,31.54391,1.610613e+09,-75.174841,6.769251,3.901482,15.726202,0.0,1.0,2.0,245.858975,2.104268,3.220370,2.876165,2.104268,8.747845,0.902907,1.374857,2.172346,4.493967,7.266030,2.534224,2.951801,6.76576,13.312782,13.265497,Driving Layup Shot,47,Made Shot,20151028,253,21500010,Shot Chart Detail,HOU,-223.9466,-1.7248,0,2,201951,Ty Lawson,2.0,47,1,2,1,54.80,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612745,Houston Rockets,DEN,54.80,55.80,21500010,253,1,42,2,9:08 PM,0:47,Lawson 2' Driving Layup (9 PTS),NaN,None,50 - 46,-4.0,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,89.42248,2.60534,6.76576,1.610613e+09,2772.0,85.90187,37.35275,1.610613e+09,201147.0,65.97291,18.99183,1.610613e+09,201951.0,87.51795,31.54391,1.610613e+09,201935.0,87.72392,15.59148,1.610613e+09,1626149.0,85.35188,28.65391,1.610613e+09,200751.0,89.40882,2.12759,1.610613e+09,202702.0,85.44611,28.23800,1.610613e+09,201568.0,65.60755,25.94692,1.610613e+09,203115.0,77.13878,44.07385,1.610613e+09,1626144.0,85.24293,25.59605,87.51795,31.54391,-2.27502,-5.94786,6.368104,-2.07184,-3.30591,3.901482,-10.37917,12.52994,16.270420,-21.91040,-5.59699,22.613976,1.89087,-29.41632,29.477030,-2.16607,-2.89000,3.611642,-1.61608,5.80884,6.029456,0.20597,-15.95243,15.953760,-21.54504,-12.55208,24.934784,87.41014,32.00039,-2.15170,-5.16696,5.597079,-2.17916,-4.55475,5.049206,-9.01411,13.04142,15.853480,-23.62974,-6.29985,24.455116,2.01253,-29.88055,29.948248,-2.25326,-3.56592,4.218171,-1.37360,6.24054,6.389923,0.19017,-14.47531,14.476559,-21.95345,-12.61050,25.317557,87.13878,32.27630,-1.75574,-4.56210,4.888290,-2.10406,-5.54119,5.927213,-7.46456,13.53337,15.455477,-24.55723,-7.09833,25.562547,2.10563,-30.21343,30.286714,-1.77918,-4.09919,4.468651,-1.13656,6.64920,6.745638,0.04219,-12.94309,12.943159,-22.02957,-12.34615,25.253304,86.75814,32.49673,-1.11143,-4.51366,4.648484,-2.05062,-5.93573,6.279963,-5.55404,13.99638,15.058088,-24.74707,-8.08737,26.035035,1.94030,-30.71025,30.771484,-1.11143,-4.51366,4.648484,-0.80131,7.11148,7.156483,-0.37426,-11.27531,11.281520,-21.53668,-11.78959,24.552454,86.45784,32.75413,-0.65819,-4.86329,4.907627,-2.14770,-6.07009,6.438836,-4.03200,14.19016,14.751870,-24.39440,-9.00588,26.003704,1.85607,-31.05748,31.112892,-0.65819,-4.86329,4.907627,-0.39855,7.39387,7.404604,-0.74475,-10.05219,10.079741,-20.58744,-11.24593,23.458764,86.16404,33.15477,-0.17211,-5.13771,5.140592,-2.22384,-6.48244,6.853283,-2.55734,14.22985,14.457822,-23.79582,-10.32273,25.938385,1.92166,-31.40079,31.459536,-0.17211,-5.13771,5.140592,0.16472,7.38993,7.391766,-1.05875,-9.21658,9.277192,-19.52151,-11.36581,22.589179,3.611642,1,1,16.512635,1,4,21500010_
20517,2.0,66.98799,21.24101,1.610613e+09,9.584118,22.577137,11.530894,20.394683,0.0,0.0,0.0,187.213257,6.581557,1.185672,6.581557,4.020846,10.954026,12.881115,7.357981,2.419856,9.194885,1.655956,18.405145,-5.399755,4.42687,19.226431,19.152433,Fadeaway Jump Shot,623,Missed Shot,20151028,144,21500010,Shot Chart Detail,HOU,-17.5115,69.9126,10,2,201951,Ty Lawson,2.0,23,1,9,0,616.11,2PT Field Goal,Center(C),In The Paint (Non-RA),8-16 ft.,1610612745,Houston Rockets,DEN,616.11,617.11,21500010,144,2,63,2,8:43 PM,10:23,MISS Lawson 10' Fadeaway Jumper,NaN,None,None,None,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,82.25874,23.24885,4.42687,1.610613e+09,2772.0,85.47158,35.51260,1.610613e+09,201951.0,66.98799,21.24101,1.610613e+09,201976.0,85.85512,15.55150,1.610613e+09,203093.0,76.18339,25.88822,1.610613e+09,1626149.0,80.75807,20.27973,1.610613e+09,2749.0,50.76455,29.50992,1.610613e+09,200751.0,82.93016,48.50277,1.610613e+09,201589.0,70.13931,32.33293,1.610613e+09,203115.0,86.34612,3.28595,1.610613e+09,1626144.0,81.14634,22.84854,66.98799,21.24101,3.15132,11.09192,11.530894,-16.22344,8.26891,18.209198,14.15835,1.60753,14.249317,19.35813,-17.95506,26.403056,15.94217,27.26176,31.580949,9.19540,4.64721,10.303006,13.77008,-0.96128,13.803592,18.86713,-5.68951,19.706322,18.48359,14.27159,23.352117,66.07808,21.83184,2.95975,10.11494,10.539076,-16.38962,7.55050,18.045212,12.16670,-0.26278,12.169537,21.07961,-18.73721,28.203422,17.46355,26.77969,31.970727,8.09248,3.38102,8.770378,12.38841,-3.20847,12.797147,19.24939,-6.59292,20.347128,19.43544,13.53367,23.683255,65.05044,22.43298,2.50281,8.99983,9.341360,-16.70148,6.71037,17.999125,10.04361,-2.68208,10.395559,22.38924,-19.75838,29.860872,19.07525,26.22326,32.427219,7.20895,1.97805,7.475402,10.93879,-5.23201,12.125636,19.63628,-7.63753,21.069299,20.52444,12.62545,24.096776,63.84930,22.95810,1.77292,7.86690,8.064202,-16.56162,-1.79927,16.659070,8.07287,-5.58625,9.817200,23.47520,-20.54836,31.198079,20.88946,25.76514,33.169443,6.21090,0.60250,6.240055,9.96526,-7.47658,12.458156,20.21675,-8.68332,22.002660,21.74599,11.81399,24.747898,62.51553,23.54658,0.95089,6.87987,6.945272,-13.39851,-1.96735,13.542176,6.55289,-8.81536,10.984122,24.09222,-21.54204,32.318641,22.67129,25.21710,33.910021,5.47011,-0.82811,5.532438,9.38925,-9.37051,13.265160,20.88772,-9.83833,23.088733,22.95740,10.91854,25.421580,61.04371,24.06633,0.15258,6.12924,6.131139,-9.95147,-1.90709,10.132559,5.16283,-11.96729,13.033451,24.58370,-22.27224,33.172443,24.29208,24.69845,34.642728,4.90653,-2.08622,5.331637,9.11168,-11.10140,14.361887,21.57918,-10.90646,24.178749,24.08429,10.31147,26.198844,10.303006,1,0,14.479653,0,3,21500010_
20516,2.0,67.36182,12.14804,1.610613e+09,30.419939,25.382382,10.221646,20.558243,0.0,0.0,0.0,354.869652,1.534934,1.949943,1.534934,8.772274,2.103733,1.454257,2.612906,6.982576,1.554772,2.304180,11.242772,11.271758,5.22510,11.743941,11.614508,Jump Shot,665,Made Shot,20151028,140,21500010,Shot Chart Detail,HOU,-125.7321,213.0674,11,2,201951,Ty Lawson,2.0,5,1,25,1,668.11,3PT Field Goal,Left Side Center(LC),Above the Break 3,24+ ft.,1610612745,Houston Rockets,DEN,668.11,669.08,21500010,140,1,1,2,8:42 PM,11:05,Lawson 26' 3PT Jump Shot (7 PTS) (Harrell 1 AST),NaN,None,29 - 27,-2.0,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,4,1626149,Montrezl Harrell,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,67.94326,12.42679,5.22510,1.610613e+09,2772.0,86.30167,2.28039,1.610613e+09,201951.0,67.36182,12.14804,1.610613e+09,201976.0,76.21493,43.26943,1.610613e+09,203093.0,82.82488,19.58182,1.610613e+09,1626149.0,79.65485,31.08435,1.610613e+09,2749.0,87.69316,34.86361,1.610613e+09,200751.0,86.60760,8.44797,1.610613e+09,201589.0,83.89974,29.27085,1.610613e+09,203115.0,83.91862,20.79889,1.610613e+09,1626144.0,73.16101,20.56537,67.36182,12.14804,16.55680,8.65085,18.680600,5.79919,8.41733,10.221646,19.24578,-3.70007,19.598229,16.53792,17.12281,23.805323,20.33134,22.71557,30.485415,15.46306,7.43378,17.157136,18.93985,-9.86765,21.356227,12.29303,18.93631,22.576590,8.85311,31.12139,32.356120,67.14119,12.20351,16.69430,8.96981,18.951442,7.99109,10.46379,13.166185,19.37817,-2.61019,19.553173,16.84538,17.06290,23.977268,20.83974,23.00920,31.043809,15.23896,7.97427,17.199270,19.03558,-9.81826,21.418486,12.95247,18.77370,22.808294,10.81389,31.67076,33.466061,66.77229,12.43318,17.10506,9.05983,19.356229,10.19624,12.27953,15.960895,19.71621,-1.45247,19.769638,17.27273,16.99970,24.235037,21.53832,23.13389,31.608165,15.07683,8.08447,17.107585,19.24552,-9.86593,21.626988,13.66188,18.44187,22.951025,12.99204,31.84054,34.389142,66.47918,12.78064,17.53789,9.24519,19.825517,12.31674,13.37897,18.185129,20.23127,-0.17492,20.232026,17.60786,17.03936,24.502582,22.27133,23.08607,32.077699,14.98113,7.67822,16.834171,19.38854,-9.86263,21.752861,14.25710,18.15138,23.081107,15.10380,31.61851,35.040761,66.26354,12.97911,17.88591,9.61264,20.305384,14.27944,14.02083,20.012148,21.07749,1.07008,21.104636,17.86683,17.35189,24.906058,23.03357,23.16457,32.667149,14.81626,7.36310,16.544993,19.43735,-9.51398,21.640850,14.58580,18.37267,23.458486,17.11130,31.22778,35.608578,66.14761,13.00971,18.15730,9.99060,20.724373,15.54082,14.35366,21.155251,21.92717,2.05054,22.022840,18.07428,17.73446,25.321743,23.59224,23.34884,33.192802,14.71559,7.13420,16.353758,19.39340,-8.99757,21.378967,14.71699,18.80016,23.875423,18.55703,30.83392,35.987414,17.157136,1,0,23.205145,0,4,21500010_
20515,2.0,80.31432,33.58475,1.610613e+09,-43.852533,12.391300,4.716759,10.980877,0.0,1.0,1.0,856.674941,12.136471,1.607604,12.136471,3.889281,2.151662,5.060941,1.471113,1.622147,4.324204,9.495255,13.967107,-1.776716,4.11631,13.020998,12.750664,Running Jump Shot,393,Missed Shot,20151028,60,21500010,Shot Chart Detail,HOU,73.1273,90.0030,6,1,201951,Ty Lawson,1.0,33,1,11,0,396.19,2PT Field Goal,Right Side(R),Mid-Range,8-16 ft.,1610612745,Houston Rockets,DEN,396.19,397.18,21500010,60,2,46,1,8:25 PM,6:33,MISS Lawson 12' Running Jump Shot,NaN,None,None,None,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,80.24970,32.31273,4.11631,1.610613e+09,2772.0,86.03665,1.94000,1.610613e+09,201951.0,80.31432,33.58475,1.610613e+09,201935.0,58.47088,6.35541,1.610613e+09,1626149.0,91.18312,17.71665,1.610613e+09,203991.0,52.76189,27.30973,1.610613e+09,202702.0,86.37971,25.64938,1.610613e+09,201568.0,86.54924,17.47582,1.610613e+09,203914.0,76.45388,18.89210,1.610613e+09,203530.0,73.40922,30.09933,1.610613e+09,1626144.0,84.92381,32.58454,80.31432,33.58475,4.60949,-1.00021,4.716759,-6.90510,-3.48542,7.734892,-3.86044,-14.69265,15.191345,6.06539,-7.93537,9.987945,6.23492,-16.10893,17.273444,-27.55243,-6.27502,28.257959,10.86880,-15.86810,19.233497,-21.84344,-27.22934,34.908063,5.72233,-31.64475,32.157974,79.41012,34.35384,3.65033,-0.67202,3.711673,-7.87131,-4.02608,8.841201,-3.46710,-15.48579,15.869167,7.02155,-8.93115,11.360792,7.05555,-16.98576,18.392847,-29.25427,-7.06384,30.095019,11.59097,-17.04971,20.616576,-21.64704,-28.00101,35.392809,6.63000,-32.54291,33.211412,77.99008,35.43424,2.14806,-0.52112,2.210368,-8.40136,-5.04988,9.802252,-2.75157,-16.52079,16.748362,8.34904,-10.43993,13.367820,8.52069,-18.17344,20.071773,-30.42207,-8.13831,31.491815,12.83937,-18.48630,22.507614,-20.97052,-29.03122,35.813049,8.03765,-33.69532,34.640704,75.93180,36.10927,0.85268,-0.33333,0.915517,-8.17438,-5.96835,10.121348,-1.55034,-17.30481,17.374119,10.35764,-11.71368,15.636208,10.41304,-19.06899,21.726891,-26.71892,-13.35477,29.870564,14.66824,-19.43161,24.346349,-19.65237,-29.68117,35.597577,9.75417,-34.42596,35.781148,72.78095,36.67344,1.09460,-0.58844,1.242743,-6.92143,-6.66762,9.610585,0.58321,-18.08823,18.097630,13.57148,-12.62203,18.533772,13.29091,-19.99702,24.011020,-20.81529,-13.88933,25.023784,17.39031,-20.16507,26.628048,-17.32610,-30.24940,34.860005,12.33960,-35.01290,37.123697,68.89058,37.30778,2.61596,-1.38036,2.957810,-4.87825,-7.46173,8.914860,3.33288,-19.07156,19.360591,17.47471,-13.11473,21.848607,16.65485,-21.08550,26.869729,-14.07835,-14.56965,20.260174,20.53706,-20.79770,29.228670,-14.26876,-30.85125,33.991133,15.57655,-35.63154,38.887473,19.233497,2,0,29.686030,0,5,21500010_
20514,2.0,73.88463,44.99115,1.610613e+09,-52.453810,25.213898,8.832558,20.144484,0.0,0.0,0.0,507.892737,0.375091,2.434826,0.375091,7.067627,5.961423,6.206792,2.533266,10.389370,1.907776,2.162349,6.794310,10.740177,7.01583,7.594053,7.127349,Jump Shot,448,Made Shot,20151028,50,21500010,Shot Chart Detail,HOU,193.2070,149.8895,7,1,201951,Ty Lawson,1.0,28,1,24,1,450.54,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612745,Houston Rockets,DEN,450.54,451.53,21500010,50,1,1,1,8:24 PM,7:28,Lawson 25' 3PT Jump Shot (3 PTS) (Harden 1 AST),NaN,None,12 - 4,-8.0,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,4,201935,James Harden,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,74.26105,44.32070,7.01583,1.610613e+09,2772.0,62.23326,29.89747,1.610613e+09,201951.0,73.88463,44.99115,1.610613e+09,201935.0,72.21481,11.83185,1.610613e+09,1626149.0,92.88363,30.23244,1.610613e+09,203991.0,87.03349,27.41678,1.610613e+09,202702.0,90.30158,29.58773,1.610613e+09,201568.0,73.53310,36.16559,1.610613e+09,203914.0,79.36219,17.02551,1.610613e+09,203530.0,86.08265,29.19362,1.610613e+09,1626144.0,77.63773,24.40830,73.88463,44.99115,12.19802,-15.79753,19.958799,-0.35153,-8.82556,8.832558,16.41695,-15.40342,22.511810,3.75310,-20.58285,20.922224,5.47756,-27.96564,28.497029,13.14886,-17.57437,21.948827,-11.65137,-15.09368,19.067606,18.99900,-14.75871,24.057879,-1.66982,-33.15930,33.201317,73.79130,45.03071,12.30133,-15.28972,19.623921,-0.07108,-11.20184,11.202066,17.03407,-14.90919,22.637215,4.84106,-21.74656,22.278885,6.14212,-27.80513,28.475444,14.22802,-17.15332,22.286160,-11.72430,-14.74081,18.834827,19.03797,-13.01468,23.061357,-0.31656,-32.51707,32.518611,73.74000,45.11832,12.55942,-14.93695,19.515417,0.10570,-13.38579,13.386207,17.60025,-14.57643,22.852595,5.62225,-23.20267,23.874120,6.57601,-27.64414,28.415531,14.75402,-15.72127,21.560135,-11.99349,-14.44532,18.775278,18.96248,-11.32392,22.086349,1.14569,-32.13867,32.159084,73.68539,45.36038,12.73407,-14.91423,19.610987,0.16283,-15.77303,15.773870,17.41666,-14.02589,22.362147,6.03932,-24.86309,25.586063,6.95040,-27.67363,28.533101,14.58938,-14.16727,20.336213,-12.30230,-14.27769,18.846724,18.84320,-10.70110,21.669788,2.69701,-32.12197,32.234994,73.72253,45.46134,12.72959,-14.46112,19.265681,0.20219,-18.00279,18.003925,17.10098,-13.64362,21.876743,5.98398,-26.30011,26.972278,7.22138,-28.01066,28.926552,13.83824,-12.60443,18.718134,-12.70527,-14.01742,18.918561,18.39686,-9.98247,20.930699,4.01304,-31.93403,32.185195,73.78966,45.35014,12.57484,-14.03443,18.843880,0.05687,-19.46525,19.465333,16.90693,-13.28578,21.502470,5.64053,-27.42498,27.999020,7.46068,-28.27914,29.246735,13.11203,-11.79005,17.633225,-13.13274,-13.62906,18.926704,18.21117,-9.28229,20.440343,5.08981,-31.38765,31.797653,19.067606,1,0,23.016219,0,6,21500010_

In [5]:
# Add Main Action type
data_train = add_shot_main_action_type_column(data_train)
data_test = add_shot_main_action_type_column(data_test)

In [6]:
data_train.shape

(44403, 314)

In [7]:
data_test.shape

(13107, 314)

# Define columns

In [8]:
# TARGET
TARGET = "SHOT_MADE_FLAG"  


# FEATURE GROUPS
tracking_features = [
    # t0
    "shooter_x_t0", "shooter_y_t0",
    "defender1_dx_t0", "defender1_dy_t0", "defender1_dist_t0",
    "defender2_dx_t0", "defender2_dy_t0", "defender2_dist_t0",
    "defender3_dx_t0", "defender3_dy_t0", "defender3_dist_t0",
    "defender4_dx_t0", "defender4_dy_t0", "defender4_dist_t0",
    "defender5_dx_t0", "defender5_dy_t0", "defender5_dist_t0",
    "attacker1_dx_t0", "attacker1_dy_t0", "attacker1_dist_t0",
    "attacker2_dx_t0", "attacker2_dy_t0", "attacker2_dist_t0",
    "attacker3_dx_t0", "attacker3_dy_t0", "attacker3_dist_t0",
    "attacker4_dx_t0", "attacker4_dy_t0", "attacker4_dist_t0",

    # t1
    "shooter_x_t1", "shooter_y_t1",
    "defender1_dx_t1", "defender1_dy_t1", "defender1_dist_t1",
    "defender2_dx_t1", "defender2_dy_t1", "defender2_dist_t1",
    "defender3_dx_t1", "defender3_dy_t1", "defender3_dist_t1",
    "defender4_dx_t1", "defender4_dy_t1", "defender4_dist_t1",
    "defender5_dx_t1", "defender5_dy_t1", "defender5_dist_t1",
    "attacker1_dx_t1", "attacker1_dy_t1", "attacker1_dist_t1",
    "attacker2_dx_t1", "attacker2_dy_t1", "attacker2_dist_t1",
    "attacker3_dx_t1", "attacker3_dy_t1", "attacker3_dist_t1",
    "attacker4_dx_t1", "attacker4_dy_t1", "attacker4_dist_t1",

    # t2
    "shooter_x_t2", "shooter_y_t2",
    "defender1_dx_t2", "defender1_dy_t2", "defender1_dist_t2",
    "defender2_dx_t2", "defender2_dy_t2", "defender2_dist_t2",
    "defender3_dx_t2", "defender3_dy_t2", "defender3_dist_t2",
    "defender4_dx_t2", "defender4_dy_t2", "defender4_dist_t2",
    "defender5_dx_t2", "defender5_dy_t2", "defender5_dist_t2",
    "attacker1_dx_t2", "attacker1_dy_t2", "attacker1_dist_t2",
    "attacker2_dx_t2", "attacker2_dy_t2", "attacker2_dist_t2",
    "attacker3_dx_t2", "attacker3_dy_t2", "attacker3_dist_t2",
    "attacker4_dx_t2", "attacker4_dy_t2", "attacker4_dist_t2",

    # t3
    "shooter_x_t3", "shooter_y_t3",
    "defender1_dx_t3", "defender1_dy_t3", "defender1_dist_t3",
    "defender2_dx_t3", "defender2_dy_t3", "defender2_dist_t3",
    "defender3_dx_t3", "defender3_dy_t3", "defender3_dist_t3",
    "defender4_dx_t3", "defender4_dy_t3", "defender4_dist_t3",
    "defender5_dx_t3", "defender5_dy_t3", "defender5_dist_t3",
    "attacker1_dx_t3", "attacker1_dy_t3", "attacker1_dist_t3",
    "attacker2_dx_t3", "attacker2_dy_t3", "attacker2_dist_t3",
    "attacker3_dx_t3", "attacker3_dy_t3", "attacker3_dist_t3",
    "attacker4_dx_t3", "attacker4_dy_t3", "attacker4_dist_t3",

    # t4
    "shooter_x_t4", "shooter_y_t4",
    "defender1_dx_t4", "defender1_dy_t4", "defender1_dist_t4",
    "defender2_dx_t4", "defender2_dy_t4", "defender2_dist_t4",
    "defender3_dx_t4", "defender3_dy_t4", "defender3_dist_t4",
    "defender4_dx_t4", "defender4_dy_t4", "defender4_dist_t4",
    "defender5_dx_t4", "defender5_dy_t4", "defender5_dist_t4",
    "attacker1_dx_t4", "attacker1_dy_t4", "attacker1_dist_t4",
    "attacker2_dx_t4", "attacker2_dy_t4", "attacker2_dist_t4",
    "attacker3_dx_t4", "attacker3_dy_t4", "attacker3_dist_t4",
    "attacker4_dx_t4", "attacker4_dy_t4", "attacker4_dist_t4",

    # t5
    "shooter_x_t5", "shooter_y_t5",
    "defender1_dx_t5", "defender1_dy_t5", "defender1_dist_t5",
    "defender2_dx_t5", "defender2_dy_t5", "defender2_dist_t5",
    "defender3_dx_t5", "defender3_dy_t5", "defender3_dist_t5",
    "defender4_dx_t5", "defender4_dy_t5", "defender4_dist_t5",
    "defender5_dx_t5", "defender5_dy_t5", "defender5_dist_t5",
    "attacker1_dx_t5", "attacker1_dy_t5", "attacker1_dist_t5",
    "attacker2_dx_t5", "attacker2_dy_t5", "attacker2_dist_t5",
    "attacker3_dx_t5", "attacker3_dy_t5", "attacker3_dist_t5",
    "attacker4_dx_t5", "attacker4_dy_t5", "attacker4_dist_t5",
]

additional_features = [
    "shot_angle",
    "distance_to_basket_tracking",
    "nearest_defender_dist",
    "avg_defender_dist",
    "defenders_within_3ft",
    "defenders_within_5ft",
    "defenders_within_7ft",
    "defender_closing_speed",
    "defenders_between",
    "has_screen",
    "teammate_between_defender",
    "players_in_paint",
    "shooter_speed",
    "nearest_teammate_distance"
]

continuous_features = (
    tracking_features +
    additional_features
)

categorical_features = [
    "PERIOD",
    "MAIN_ACTION_TYPE"
]

player_feature = "PLAYER_ID"

In [9]:
required_columns = (
    continuous_features +
    categorical_features +
    [player_feature, TARGET]
)

data_train = data_train.dropna(subset=required_columns).copy()
data_test = data_test.dropna(subset=required_columns).copy()

# Label encoding for categorical and ID features

In [10]:
# Label encode MAIN_ACTION_TYPE
UNKNOWN_ACTION_IDX = 0
unique_actions = data_train['MAIN_ACTION_TYPE'].unique()

action_to_idx = {
    action: idx + 1
    for idx, action in enumerate(unique_actions)
}

data_train['MAIN_ACTION_TYPE'] = (
    data_train['MAIN_ACTION_TYPE']
    .map(action_to_idx)
    .fillna(UNKNOWN_ACTION_IDX)
    .astype(int)
)

data_test['MAIN_ACTION_TYPE'] = (
    data_test['MAIN_ACTION_TYPE']
    .map(action_to_idx)
    .fillna(UNKNOWN_ACTION_IDX)
    .astype(int)
)

num_actions = max(action_to_idx.values()) + 1

In [11]:
# LABEL ENCODE PLAYER IDS

unique_players = data_train[player_feature].unique()

player_to_idx = {
    player_id: idx + 1
    for idx, player_id in enumerate(unique_players)
}

UNKNOWN_PLAYER_IDX = 0


# Encode Train/Test
data_train[player_feature] = (
    data_train[player_feature]
    .map(player_to_idx)
    .fillna(UNKNOWN_PLAYER_IDX)
    .astype(int)
)

data_test[player_feature] = (
    data_test[player_feature]
    .map(player_to_idx)
    .fillna(UNKNOWN_PLAYER_IDX)
    .astype(int)
)

num_players = max(player_to_idx.values()) + 1

In [12]:
# TRAIN / VALIDATION / TEST SPLIT
# We need validation for early stopping

X_train = data_train.drop('SHOT_MADE_FLAG', axis=1)
y_train = data_train['SHOT_MADE_FLAG']

X_test = data_test.drop('SHOT_MADE_FLAG', axis=1)
y_test = data_test['SHOT_MADE_FLAG']

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=42)

# Feature definition

In [13]:
# CONTINUOUS FEATURES
X_train_cont = X_train[continuous_features].values
X_valid_cont = X_val[continuous_features].values
X_test_cont = X_test[continuous_features].values


# STANDARDIZATION
scaler = StandardScaler()

X_train_cont = scaler.fit_transform(X_train_cont)
X_valid_cont = scaler.transform(X_valid_cont)
X_test_cont = scaler.transform(X_test_cont)


# PERIOD INPUT
X_train_period = X_train["PERIOD"].values
X_valid_period = X_val["PERIOD"].values
X_test_period = X_test["PERIOD"].values

# MAIN ACTION TYPE Input
X_train_action = X_train["MAIN_ACTION_TYPE"].values
X_valid_action = X_val["MAIN_ACTION_TYPE"].values
X_test_action = X_test["MAIN_ACTION_TYPE"].values

# PLAYER INPUT
X_train_player = X_train[player_feature].values
X_valid_player = X_val[player_feature].values
X_test_player = X_test[player_feature].values


# TARGET
y_train = y_train.values
y_valid = y_val.values
y_test = y_test.values

# Model Definition

In [14]:
# ==========================
# MODEL
# ==========================

# Continuous Input
continuous_input = Input(
    shape=(len(continuous_features),),
    name="continuous_input"
)

x = Dense(512, activation="relu")(continuous_input)
x = BatchNormalization()(x)
x = Dropout(0.20)(x)

x = Dense(256, activation="relu")(x)
x = BatchNormalization()(x)
x = Dropout(0.20)(x)

x = Dense(128, activation="relu")(x)
x = BatchNormalization()(x)


# PLAYER EMBEDDING
player_input = Input(
    shape=(1,),
    name="player_input"
)

player_embedding = Embedding(
    input_dim=num_players + 1,
    output_dim=16,
    name="player_embedding"
)(player_input)

player_embedding = Flatten()(player_embedding)

# PERIOD EMBEDDING
period_input = Input(
    shape=(1,),
    name="period_input"
)

period_embedding = Embedding(
    input_dim=10,
    output_dim=4,
    name="period_embedding"
)(period_input)

period_embedding = Flatten()(period_embedding)

# ACTION TYPE EMBEDDING
action_input = Input(
    shape=(1,),
    name="action_input"
)

action_embedding = Embedding(
    input_dim=num_actions,
    output_dim=4,
    name="action_embedding"
)(action_input)

action_embedding = Flatten()(action_embedding)


# CONCATENATE
x = Concatenate()([
    x,
    player_embedding,
    period_embedding,
    action_embedding
])

x = Dense(64, activation="relu")(x)
x = Dropout(0.20)(x)

output = Dense(
    1,
    activation="sigmoid"
)(x)


# ========================
# BUILD MODEL
# ========================

model = Model(
    inputs=[
        continuous_input,
        player_input,
        period_input,
        action_input
    ],
    outputs=output
)

model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.AUC(name="auc")
    ]
)

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ continuous_input (InputLayer) │ (None, 188)               │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense (Dense)                 │ (None, 512)               │          96,768 │ continuous_input[0][0]     │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ batch_normalization           │ (None, 512)               │           2,048 │ dense[0][0]                │
│ (BatchNormalization)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout (Dropout)             │ (None, 512)               │               0 │ batch_normalization[0][0]  │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_1 (Dense)               │ (None, 256)               │         131,328 │ dropout[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ batch_normalization_1         │ (None, 256)               │           1,024 │ dense_1[0][0]              │
│ (BatchNormalization)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout_1 (Dropout)           │ (None, 256)               │               0 │ batch_normalization_1[0][… │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ player_input (InputLayer)     │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ period_input (InputLayer)     │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ action_input (InputLayer)     │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_2 (Dense)               │ (None, 128)               │          32,896 │ dropout_1[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ player_embedding (Embedding)  │ (None, 1, 16)             │           6,640 │ player_input[0][0]         │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ period_embedding (Embedding)  │ (None, 1, 4)              │              40 │ period_input[0][0]         │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ action_embedding (Embedding)  │ (None, 1, 4)              │              24 │ action_input[0][0]         │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ batch_normalization_2         │ (None, 128)               │             512 │ dense_2[0][0]              │
│ (BatchNormalization)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten (Flatten)             │ (None, 16)                │               0 │ player_embedding[0][0]     │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten_1 (Flatten)           │ (None, 4)                 │               0 │ period_embedding[0][0]     │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten_2 (Flatten)           │ (None, 4)                 │               0 │ action_embedding[0][0]     │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ concatenate (Concatenate)     │ (None, 152)               │               0 │ batch_normalization_2[0][… │
│                               │                           │                 │ flatten[0][0],             │
│                               │                           │                 │ flatten_1[0][0],           │
│                               │                           │                 │ flatten_2[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_3 (Dense)               │ (None, 64)                │           9,792 │ concatenate[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout_2 (Dropout)           │ (None, 64)                │               0 │ dense_3[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_4 (Dense)               │ (None, 1)                 │              65 │ dropout_2[0][0]            │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 281,137 (1.07 MB)

 Trainable params: 279,345 (1.07 MB)

 Non-trainable params: 1,792 (7.00 KB)

In [15]:
# Early stopping callback

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

In [16]:
# TRAIN

history = model.fit(
    x=[
        X_train_cont,
        X_train_player,
        X_train_period,
        X_train_action
    ],
    y=y_train,

    validation_data=(
        [
            X_valid_cont,
            X_valid_player,
            X_valid_period,
            X_valid_action
        ],
        y_valid
    ),

    epochs=100,
    batch_size=256,
    callbacks=[early_stopping],
    verbose=1
)

Epoch 1/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 6s 19ms/step - auc: 0.5599 - loss: 0.7133 - val_auc: 0.6093 - val_loss: 0.6682
Epoch 2/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6278 - loss: 0.6590 - val_auc: 0.6171 - val_loss: 0.6564
Epoch 3/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6420 - loss: 0.6492 - val_auc: 0.6264 - val_loss: 0.6535
Epoch 4/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6527 - loss: 0.6435 - val_auc: 0.6309 - val_loss: 0.6534
Epoch 5/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - auc: 0.6603 - loss: 0.6395 - val_auc: 0.6273 - val_loss: 0.6542
Epoch 6/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6643 - loss: 0.6374 - val_auc: 0.6258 - val_loss: 0.6533
Epoch 7/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6719 - loss: 0.6333 - val_auc: 0.6291 - val_loss: 0.6525
Epoch 8/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6714 - loss: 0.6335 - val_auc: 0.6307 - val_loss: 0.6531
Epoch 9/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6754 - loss: 0.6308 - val_auc: 0.6282 - val_loss: 0.6550
Epoch 10/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - auc: 0.6809 - loss: 0.6280 - val_auc: 0.6310 - val_loss: 0.6547
Epoch 11/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6823 - loss: 0.6266 - val_auc: 0.6298 - val_loss: 0.6569
Epoch 12/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6867 - loss: 0.6243 - val_auc: 0.6297 - val_loss: 0.6546
Epoch 13/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6904 - loss: 0.6214 - val_auc: 0.6279 - val_loss: 0.6594
Epoch 14/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - auc: 0.6948 - loss: 0.6187 - val_auc: 0.6242 - val_loss: 0.6570
Epoch 15/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.7005 - loss: 0.6154 - val_auc: 0.6300 - val_loss: 0.6577
Epoch 16/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.7031 - loss: 0.6126 - val_auc: 0.6274 - val_loss: 0.6575
Epoch 17/100
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.7080 - loss: 0.6090 - val_auc: 0.6275 - val_loss: 0.6634

In [17]:
# PREDICTIONS

y_pred_proba = model.predict([
    X_test_cont,
    X_test_player,
    X_test_period,
    X_test_action
]).flatten()

y_pred = (y_pred_proba >= 0.5).astype(int)


# EVALUATION

auc = roc_auc_score(y_test, y_pred_proba)
ll = log_loss(y_test, y_pred_proba)
brier = brier_score_loss(y_test, y_pred_proba)

print(f"AUC:        {auc:.4f}")
print(f"Log Loss:   {ll:.4f}")
print(f"Brier:      {brier:.4f}")

405/405 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
AUC:        0.6406
Log Loss:   0.6466
Brier:      0.2284

In [18]:
display(pd.crosstab(y_test, y_pred))
print(classification_report(y_test, y_pred))

col_0     0     1
row_0
0      5737  1417
1      3463  2332

              precision    recall  f1-score   support

           0       0.62      0.80      0.70      7154
           1       0.62      0.40      0.49      5795

    accuracy                           0.62     12949
   macro avg       0.62      0.60      0.60     12949
weighted avg       0.62      0.62      0.61     12949

In [19]:
# Build error Dataframe

error_df = X_test.copy()

error_df["y_true"] = y_test
error_df["y_pred"] = y_pred
error_df["y_pred_proba"] = y_pred_proba

# confidence
error_df["confidence"] = np.where(
    error_df["y_pred"] == 1,
    error_df["y_pred_proba"],
    1 - error_df["y_pred_proba"]
)

error_df["correct"] = (
    error_df["y_true"] == error_df["y_pred"]
)

# prediction error magnitude
error_df["error"] = abs(error_df["y_true"] - error_df["y_pred_proba"])

In [20]:
for action_type in error_df["MAIN_ACTION_TYPE"].value_counts().index[:15]:

    subset = error_df[
        error_df["MAIN_ACTION_TYPE"] == action_type
    ]

    accuracy = (
        subset["y_true"] == subset["y_pred"]
    ).mean()

    print("\n" + "="*60)
    print(f"{action_type}")
    print(f"n = {len(subset)}")
    print(f"accuracy = {accuracy:.3f}")
    print(f"roc-auc = {roc_auc_score(subset["y_true"], subset["y_pred_proba"]):.3f}")
    print("="*60)

    cm = pd.crosstab(
        subset["y_true"],
        subset["y_pred"],
        rownames=["Actual"],
        colnames=["Predicted"]
    )

    display(cm)

============================================================
2
n = 8303
accuracy = 0.629
roc-auc = 0.543
============================================================

Predicted     0    1
Actual
0          5061  240
1          2839  163

============================================================
1
n = 3299
accuracy = 0.580
roc-auc = 0.585
============================================================

Predicted    0     1
Actual
0          492   975
1          409  1423

============================================================
5
n = 646
accuracy = 0.904
roc-auc = 0.642
============================================================

Predicted    1
Actual
0           62
1          584

============================================================
4
n = 511
accuracy = 0.481
roc-auc = 0.514
============================================================

Predicted    0   1
Actual
0          153  85
1          180  93

============================================================
3
n = 190
accuracy = 0.526
roc-auc = 0.528
============================================================

Predicted   0   1
Actual
0          31  55
1          35  69

In [22]:
# save model for visualization and inference
model.save("deepNN.keras")
joblib.dump(scaler, "deepNN_scaler.pkl")
joblib.dump(continuous_features, "deepNN_continuous_features.pkl")
joblib.dump(player_to_idx, "deepNN_player_to_idx.pkl")
joblib.dump(action_to_idx, "deepNN_action_to_idx.pkl")
data_test.to_parquet("example_shots.parquet")

# XGBoost for reference

In [25]:
data_train.head()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,shooter_speed,player1_speed,player2_speed,player3_speed,player4_speed,player5_speed,player6_speed,player7_speed,player8_speed,player9_speed,player10_speed,defender_closing_speed,ball_height,ball_speed,ball_xy_speed,ACTION_TYPE,EVENTTIME,EVENT_TYPE,GAME_DATE,GAME_EVENT_ID,GAME_ID,GRID_TYPE,HTM,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,SHOT_TYPE,SHOT_ZONE_AREA,SHOT_ZONE_BASIC,SHOT_ZONE_RANGE,TEAM_ID,TEAM_NAME,VTM,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_WCTIMESTRING,event_PCTIMESTRING,event_HOMEDESCRIPTION,event_NEUTRALDESCRIPTION,event_VISITORDESCRIPTION,event_SCORE,event_SCOREMARGIN,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_NAME,event_PLAYER1_TEAM_ID,event_PLAYER1_TEAM_CITY,event_PLAYER1_TEAM_NICKNAME,event_PLAYER1_TEAM_ABBREVIATION,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_NAME,event_PLAYER2_TEAM_ID,event_PLAYER2_TEAM_CITY,event_PLAYER2_TEAM_NICKNAME,event_PLAYER2_TEAM_ABBREVIATION,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_NAME,event_PLAYER3_TEAM_ID,event_PLAYER3_TEAM_CITY,event_PLAYER3_TEAM_NICKNAME,event_PLAYER3_TEAM_ABBREVIATION,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,nearest_teammate_distance,defenders_between,has_screen,offensive_spacing,teammate_between_defender,players_in_paint,match_key,MAIN_ACTION_TYPE
20518,3.0,87.51795,31.54391,1.610613e+09,-75.174841,6.769251,3.901482,15.726202,0.0,1.0,2.0,245.858975,2.104268,3.220370,2.876165,2.104268,8.747845,0.902907,1.374857,2.172346,4.493967,7.266030,2.534224,2.951801,6.76576,13.312782,13.265497,Driving Layup Shot,47,Made Shot,20151028,253,21500010,Shot Chart Detail,HOU,-223.9466,-1.7248,0,2,1,Ty Lawson,2.0,47,1,2,1,54.80,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612745,Houston Rockets,DEN,54.80,55.80,21500010,253,1,42,2,9:08 PM,0:47,Lawson 2' Driving Layup (9 PTS),NaN,None,50 - 46,-4.0,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,89.42248,2.60534,6.76576,1.610613e+09,2772.0,85.90187,37.35275,1.610613e+09,201147.0,65.97291,18.99183,1.610613e+09,201951.0,87.51795,31.54391,1.610613e+09,201935.0,87.72392,15.59148,1.610613e+09,1626149.0,85.35188,28.65391,1.610613e+09,200751.0,89.40882,2.12759,1.610613e+09,202702.0,85.44611,28.23800,1.610613e+09,201568.0,65.60755,25.94692,1.610613e+09,203115.0,77.13878,44.07385,1.610613e+09,1626144.0,85.24293,25.59605,87.51795,31.54391,-2.27502,-5.94786,6.368104,-2.07184,-3.30591,3.901482,-10.37917,12.52994,16.270420,-21.91040,-5.59699,22.613976,1.89087,-29.41632,29.477030,-2.16607,-2.89000,3.611642,-1.61608,5.80884,6.029456,0.20597,-15.95243,15.953760,-21.54504,-12.55208,24.934784,87.41014,32.00039,-2.15170,-5.16696,5.597079,-2.17916,-4.55475,5.049206,-9.01411,13.04142,15.853480,-23.62974,-6.29985,24.455116,2.01253,-29.88055,29.948248,-2.25326,-3.56592,4.218171,-1.37360,6.24054,6.389923,0.19017,-14.47531,14.476559,-21.95345,-12.61050,25.317557,87.13878,32.27630,-1.75574,-4.56210,4.888290,-2.10406,-5.54119,5.927213,-7.46456,13.53337,15.455477,-24.55723,-7.09833,25.562547,2.10563,-30.21343,30.286714,-1.77918,-4.09919,4.468651,-1.13656,6.64920,6.745638,0.04219,-12.94309,12.943159,-22.02957,-12.34615,25.253304,86.75814,32.49673,-1.11143,-4.51366,4.648484,-2.05062,-5.93573,6.279963,-5.55404,13.99638,15.058088,-24.74707,-8.08737,26.035035,1.94030,-30.71025,30.771484,-1.11143,-4.51366,4.648484,-0.80131,7.11148,7.156483,-0.37426,-11.27531,11.281520,-21.53668,-11.78959,24.552454,86.45784,32.75413,-0.65819,-4.86329,4.907627,-2.14770,-6.07009,6.438836,-4.03200,14.19016,14.751870,-24.39440,-9.00588,26.003704,1.85607,-31.05748,31.112892,-0.65819,-4.86329,4.907627,-0.39855,7.39387,7.404604,-0.74475,-10.05219,10.079741,-20.58744,-11.24593,23.458764,86.16404,33.15477,-0.17211,-5.13771,5.140592,-2.22384,-6.48244,6.853283,-2.55734,14.22985,14.457822,-23.79582,-10.32273,25.938385,1.92166,-31.40079,31.459536,-0.17211,-5.13771,5.140592,0.16472,7.38993,7.391766,-1.05875,-9.21658,9.277192,-19.52151,-11.36581,22.589179,3.611642,1,1,16.512635,1,4,21500010_,1
20517,2.0,66.98799,21.24101,1.610613e+09,9.584118,22.577137,11.530894,20.394683,0.0,0.0,0.0,187.213257,6.581557,1.185672,6.581557,4.020846,10.954026,12.881115,7.357981,2.419856,9.194885,1.655956,18.405145,-5.399755,4.42687,19.226431,19.152433,Fadeaway Jump Shot,623,Missed Shot,20151028,144,21500010,Shot Chart Detail,HOU,-17.5115,69.9126,10,2,1,Ty Lawson,2.0,23,1,9,0,616.11,2PT Field Goal,Center(C),In The Paint (Non-RA),8-16 ft.,1610612745,Houston Rockets,DEN,616.11,617.11,21500010,144,2,63,2,8:43 PM,10:23,MISS Lawson 10' Fadeaway Jumper,NaN,None,None,None,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,82.25874,23.24885,4.42687,1.610613e+09,2772.0,85.47158,35.51260,1.610613e+09,201951.0,66.98799,21.24101,1.610613e+09,201976.0,85.85512,15.55150,1.610613e+09,203093.0,76.18339,25.88822,1.610613e+09,1626149.0,80.75807,20.27973,1.610613e+09,2749.0,50.76455,29.50992,1.610613e+09,200751.0,82.93016,48.50277,1.610613e+09,201589.0,70.13931,32.33293,1.610613e+09,203115.0,86.34612,3.28595,1.610613e+09,1626144.0,81.14634,22.84854,66.98799,21.24101,3.15132,11.09192,11.530894,-16.22344,8.26891,18.209198,14.15835,1.60753,14.249317,19.35813,-17.95506,26.403056,15.94217,27.26176,31.580949,9.19540,4.64721,10.303006,13.77008,-0.96128,13.803592,18.86713,-5.68951,19.706322,18.48359,14.27159,23.352117,66.07808,21.83184,2.95975,10.11494,10.539076,-16.38962,7.55050,18.045212,12.16670,-0.26278,12.169537,21.07961,-18.73721,28.203422,17.46355,26.77969,31.970727,8.09248,3.38102,8.770378,12.38841,-3.20847,12.797147,19.24939,-6.59292,20.347128,19.43544,13.53367,23.683255,65.05044,22.43298,2.50281,8.99983,9.341360,-16.70148,6.71037,17.999125,10.04361,-2.68208,10.395559,22.38924,-19.75838,29.860872,19.07525,26.22326,32.427219,7.20895,1.97805,7.475402,10.93879,-5.23201,12.125636,19.63628,-7.63753,21.069299,20.52444,12.62545,24.096776,63.84930,22.95810,1.77292,7.86690,8.064202,-16.56162,-1.79927,16.659070,8.07287,-5.58625,9.817200,23.47520,-20.54836,31.198079,20.88946,25.76514,33.169443,6.21090,0.60250,6.240055,9.96526,-7.47658,12.458156,20.21675,-8.68332,22.002660,21.74599,11.81399,24.747898,62.51553,23.54658,0.95089,6.87987,6.945272,-13.39851,-1.96735,13.542176,6.55289,-8.81536,10.984122,24.09222,-21.54204,32.318641,22.67129,25.21710,33.910021,5.47011,-0.82811,5.532438,9.38925,-9.37051,13.265160,20.88772,-9.83833,23.088733,22.95740,10.91854,25.421580,61.04371,24.06633,0.15258,6.12924,6.131139,-9.95147,-1.90709,10.132559,5.16283,-11.96729,13.033451,24.58370,-22.27224,33.172443,24.29208,24.69845,34.642728,4.90653,-2.08622,5.331637,9.11168,-11.10140,14.361887,21.57918,-10.90646,24.178749,24.08429,10.31147,26.198844,10.303006,1,0,14.479653,0,3,21500010_,2
20516,2.0,67.36182,12.14804,1.610613e+09,30.419939,25.382382,10.221646,20.558243,0.0,0.0,0.0,354.869652,1.534934,1.949943,1.534934,8.772274,2.103733,1.454257,2.612906,6.982576,1.554772,2.304180,11.242772,11.271758,5.22510,11.743941,11.614508,Jump Shot,665,Made Shot,20151028,140,21500010,Shot Chart Detail,HOU,-125.7321,213.0674,11,2,1,Ty Lawson,2.0,5,1,25,1,668.11,3PT Field Goal,Left Side Center(LC),Above the Break 3,24+ ft.,1610612745,Houston Rockets,DEN,668.11,669.08,21500010,140,1,1,2,8:42 PM,11:05,Lawson 26' 3PT Jump Shot (7 PTS) (Harrell 1 AST),NaN,None,29 - 27,-2.0,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,4,1626149,Montrezl Harrell,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,67.94326,12.42679,5.22510,1.610613e+09,2772.0,86.30167,2.28039,1.610613e+09,201951.0,67.36182,12.14804,1.610613e+09,201976.0,76.21493,43.26943,1.610613e+09,203093.0,82.82488,19.58182,1.610613e+09,1626149.0,79.65485,31.08435,1.610613e+09,2749.0,87.69316,34.86361,1.610613e+09,200751.0,86.60760,8.44797,1.610613e+09,201589.0,83.89974,29.27085,1.610613e+09,203115.0,83.91862,20.79889,1.610613e+09,1626144.0,73.16101,20.56537,67.36182,12.14804,16.55680,8.65085,18.680600,5.79919,8.41733,10.221646,19.24578,-3.70007,19.598229,16.53792,17.12281,23.805323,20.33134,22.71557,30.485415,15.46306,7.43378,17.157136,18.93985,-9.86765,21.356227,12.29303,18.93631,22.576590,8.85311,31.12139,32.356120,67.14119,12.20351,16.69430,8.96981,18.951442,7.99109,10.46379,13.166185,19.37817,-2.61019,19.553173,16.84538,17.06290,23.977268,20.83974,23.00920,31.043809,15.23896,7.97427,17.199270,19.03558,-9.81826,21.418486,12.95247,18.77370,22.808294,10.81389,31.67076,33.466061,66.77229,12.43318,17.10506,9.05983,19.356229,10.19624,12.27953,15.960895,19.71621,-1.45247,19.769638,17.27273,16.99970,24.235037,21.53832,23.13389,31.608165,15.07683,8.08447,17.107585,19.24552,-9.86593,21.626988,13.66188,18.44187,22.951025,12.99204,31.84054,34.389142,66.47918,12.78064,17.53789,9.24519,19.825517,12.31674,13.37897,18.185129,20.23127,-0.17492,20.232026,17.60786,17.03936,24.502582,22.27133,23.08607,32.077699,14.98113,7.67822,16.834171,19.38854,-9.86263,21.752861,14.25710,18.15138,23.081107,15.10380,31.61851,35.040761,66.26354,12.97911,17.88591,9.61264,20.305384,14.27944,14.02083,20.012148,21.07749,1.07008,21.104636,17.86683,17.35189,24.906058,23.03357,23.16457,32.667149,14.81626,7.36310,16.544993,19.43735,-9.51398,21.640850,14.58580,18.37267,23.458486,17.11130,31.22778,35.608578,66.14761,13.00971,18.15730,9.99060,20.724373,15.54082,14.35366,21.155251,21.92717,2.05054,22.022840,18.07428,17.73446,25.321743,23.59224,23.34884,33.192802,14.71559,7.13420,16.353758,19.39340,-8.99757,21.378967,14.71699,18.80016,23.875423,18.55703,30.83392,35.987414,17.157136,1,0,23.205145,0,4,21500010_,2
20515,2.0,80.31432,33.58475,1.610613e+09,-43.852533,12.391300,4.716759,10.980877,0.0,1.0,1.0,856.674941,12.136471,1.607604,12.136471,3.889281,2.151662,5.060941,1.471113,1.622147,4.324204,9.495255,13.967107,-1.776716,4.11631,13.020998,12.750664,Running Jump Shot,393,Missed Shot,20151028,60,21500010,Shot Chart Detail,HOU,73.1273,90.0030,6,1,1,Ty Lawson,1.0,33,1,11,0,396.19,2PT Field Goal,Right Side(R),Mid-Range,8-16 ft.,1610612745,Houston Rockets,DEN,396.19,397.18,21500010,60,2,46,1,8:25 PM,6:33,MISS Lawson 12' Running Jump Shot,NaN,None,None,None,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,80.24970,32.31273,4.11631,1.610613e+09,2772.0,86.03665,1.94000,1.610613e+09,201951.0,80.31432,33.58475,1.610613e+09,201935.0,58.47088,6.35541,1.610613e+09,1626149.0,91.18312,17.71665,1.610613e+09,203991.0,52.76189,27.30973,1.610613e+09,202702.0,86.37971,25.64938,1.610613e+09,201568.0,86.54924,17.47582,1.610613e+09,203914.0,76.45388,18.89210,1.610613e+09,203530.0,73.40922,30.09933,1.610613e+09,1626144.0,84.92381,32.58454,80.31432,33.58475,4.60949,-1.00021,4.716759,-6.90510,-3.48542,7.734892,-3.86044,-14.69265,15.191345,6.06539,-7.93537,9.987945,6.23492,-16.10893,17.273444,-27.55243,-6.27502,28.257959,10.86880,-15.86810,19.233497,-21.84344,-27.22934,34.908063,5.72233,-31.64475,32.157974,79.41012,34.35384,3.65033,-0.67202,3.711673,-7.87131,-4.02608,8.841201,-3.46710,-15.48579,15.869167,7.02155,-8.93115,11.360792,7.05555,-16.98576,18.392847,-29.25427,-7.06384,30.095019,11.59097,-17.04971,20.616576,-21.64704,-28.00101,35.392809,6.63000,-32.54291,33.211412,77.99008,35.43424,2.14806,-0.52112,2.210368,-8.40136,-5.04988,9.802252,-2.75157,-16.52079,16.748362,8.34904,-10.43993,13.367820,8.52069,-18.17344,20.071773,-30.42207,-8.13831,31.491815,12.83937,-18.48630,22.507614,-20.97052,-29.03122,35.813049,8.03765,-33.69532,34.640704,75.93180,36.10927,0.85268,-0.33333,0.915517,-8.17438,-5.96835,10.121348,-1.55034,-17.30481,17.374119,10.35764,-11.71368,15.636208,10.41304,-19.06899,21.726891,-26.71892,-13.35477,29.870564,14.66824,-19.43161,24.346349,-19.65237,-29.68117,35.597577,9.75417,-34.42596,35.781148,72.78095,36.67344,1.09460,-0.58844,1.242743,-6.92143,-6.66762,9.610585,0.58321,-18.08823,18.097630,13.57148,-12.62203,18.533772,13.29091,-19.99702,24.011020,-20.81529,-13.88933,25.023784,17.39031,-20.16507,26.628048,-17.32610,-30.24940,34.860005,12.33960,-35.01290,37.123697,68.89058,37.30778,2.61596,-1.38036,2.957810,-4.87825,-7.46173,8.914860,3.33288,-19.07156,19.360591,17.47471,-13.11473,21.848607,16.65485,-21.08550,26.869729,-14.07835,-14.56965,20.260174,20.53706,-20.79770,29.228670,-14.26876,-30.85125,33.991133,15.57655,-35.63154,38.887473,19.233497,2,0,29.686030,0,5,21500010_,2
20514,2.0,73.88463,44.99115,1.610613e+09,-52.453810,25.213898,8.832558,20.144484,0.0,0.0,0.0,507.892737,0.375091,2.434826,0.375091,7.067627,5.961423,6.206792,2.533266,10.389370,1.907776,2.162349,6.794310,10.740177,7.01583,7.594053,7.127349,Jump Shot,448,Made Shot,20151028,50,21500010,Shot Chart Detail,HOU,193.2070,149.8895,7,1,1,Ty Lawson,1.0,28,1,24,1,450.54,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612745,Houston Rockets,DEN,450.54,451.53,21500010,50,1,1,1,8:24 PM,7:28,Lawson 25' 3PT Jump Shot (3 PTS) (Harden 1 AST),NaN,None,12 - 4,-8.0,4.0,201951,Ty Lawson,1.610613e+09,Houston,Rockets,HOU,4,201935,James Harden,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,74.26105,44.32070,7.01583,1.610613e+09,2772.0,62.23326,29.89747,1.610613e+09,201951.0,73.88463,44.99115,1.610613e+09,201935.0,72.21481,11.83185,1.610613e+09,1626149.0,92.88363,30.23244,1.610613e+09,203991.0,87.03349,27.41678,1.610613e+09,202702.0,90.30158,29.58773,1.610613e+09,201568.0,73.53310,36.16559,1.610613e+09,203914.0,79.36219,17.02551,1.610613e+09,203530.0,86.08265,29.19362,1.610613e+09,1626144.0,77.63773,24.40830,73.88463,44.99115,12.19802,-15.79753,19.958799,-0.35153,-8.82556,8.832558,16.41695,-15.40342,22.511810,3.75310,-20.58285,20.922224,5.47756,-27.96564,28.497029,13.14886,-17.57437,21.948827,-11.65137,-15.09368,19.067606,18.99900,-14.75871,24.057879,-1.66982,-33.15930,33.201317,73.79130,45.03071,12.30133,-15.28972,19.623921,-0.07108,-11.20184,11.202066,17.03407,-14.90919,22.637215,4.84106,-21.74656,22.278885,6.14212,-27.80513,28.475444,14.22802,-17.15332,22.286160,-11.72430,-14.74081,18.834827,19.03797,-13.01468,23.061357,-0.31656,-32.51707,32.518611,73.74000,45.11832,12.55942,-14.93695,19.515417,0.10570,-13.38579,13.386207,17.60025,-14.57643,22.852595,5.62225,-23.20267,23.874120,6.57601,-27.64414,28.415531,14.75402,-15.72127,21.560135,-11.99349,-14.44532,18.775278,18.96248,-11.32392,22.086349,1.14569,-32.13867,32.159084,73.68539,45.36038,12.73407,-14.91423,19.610987,0.16283,-15.77303,15.773870,17.41666,-14.02589,22.362147,6.03932,-24.86309,25.586063,6.95040,-27.67363,28.533101,14.58938,-14.16727,20.336213,-12.30230,-14.27769,18.846724,18.84320,-10.70110,21.669788,2.69701,-32.12197,32.234994,73.72253,45.46134,12.72959,-14.46112,19.265681,0.20219,-18.00279,18.003925,17.10098,-13.64362,21.876743,5.98398,-26.30011,26.972278,7.22138,-28.01066,28.926552,13.83824,-12.60443,18.718134,-12.70527,-14.01742,18.918561,18.39686,-9.98247,20.930699,4.01304,-31.93403,32.185195,73.78966,45.35014,12.57484,-14.03443,18.843880,0.05687,-19.46525,19.465333,16.90693,-13.28578,21.502470,5.64053,-27.42498,27.999020,7.46068,-28.27914,29.246735,13.11203,-11.79005,17.633225,-13.13274,-13.62906,18.926704,18.21117,-9.28229,20.440343,5.08981,-31.38765,31.797653,19.067606,1,0,23.016219,0,6,21500010_,2

In [26]:
feature_set_reduced = ['MAIN_ACTION_TYPE']
feature_set_reduced.extend(['shooter_x', 'shooter_y', 'shot_angle', 'distance_to_basket_tracking', 'nearest_defender_dist',
    'avg_defender_dist', 'defenders_within_3ft', 'defenders_within_5ft', 'defenders_within_7ft',
    'shooter_speed', 'defender_closing_speed',
    'nearest_teammate_distance', 'defenders_between', 'has_screen', 'offensive_spacing', 'teammate_between_defender', 'players_in_paint'])

cols_OneHot = ['MAIN_ACTION_TYPE']

In [27]:
encoder_oh = OneHotEncoder(sparse_output=False, drop='first', handle_unknown="ignore")
column_encoder = make_column_transformer(
    (encoder_oh, cols_OneHot),
    remainder='passthrough',
    verbose_feature_names_out=False
)
column_encoder.set_output(transform="pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['MAIN_ACTION_TYPE'])],
                  verbose_feature_names_out=False)

In [28]:
def select_features(df_):
    return df_[feature_set_reduced]

pipeline = Pipeline([
    ("feature_selection",
     FunctionTransformer(select_features)),
    ("encoding",
     column_encoder),
    ("model",
     XGBClassifier(
         n_estimators=500,
         max_depth=3,
         learning_rate=0.01,
         subsample=0.7,
         min_child_weight=1,
         gamma=0,
         random_state=42,
         n_jobs=-1,
         eval_metric="logloss"
     ))
])
pipeline.fit(X_train, y_train)

Pipeline(steps=[('feature_selection',
                 FunctionTransformer(func=<function select_features at 0x000002E78D2CEE80>)),
                ('encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['MAIN_ACTION_TYPE'])],
                                   verbose_feature_names_out=False)),
                ('model',
                 XGBClassifier(bas...
                               feature_types=None, feature_weights=None,
                               gamma=0, grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=0.01,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None, min_child_weight=1,
                               missing=nan, monotone_constraints=None,
                               multi_strategy=None, n_estimators=500, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [29]:
# General metrics

y_pred_proba = pipeline.predict_proba(X_test)
y_pred = pipeline.predict(X_test)

print(roc_auc_score(y_test, y_pred_proba[:,1]))
display(pd.crosstab(y_test, y_pred))
print(classification_report(y_test, y_pred))

print("Brier score: ", brier_score_loss(y_test, y_pred_proba[:,1]))

0.6414395079482738

col_0     0     1
row_0
0      5557  1597
1      3249  2546

              precision    recall  f1-score   support

           0       0.63      0.78      0.70      7154
           1       0.61      0.44      0.51      5795

    accuracy                           0.63     12949
   macro avg       0.62      0.61      0.60     12949
weighted avg       0.62      0.63      0.61     12949

Brier score:  0.2275005578994751

# Lookup table for reference

In [43]:
train_lookup = X_train.copy()

train_lookup["y"] = y_train.values

lookup_table = (
    train_lookup
    .groupby(
        ["MAIN_ACTION_TYPE", "PLAYER_NAME"]
    )["y"]
    .mean()
    .reset_index()
    .rename(columns={"y": "p_make"})
)

lookup_table.head()

lookup_dict = {
    (
        row["MAIN_ACTION_TYPE"],
        row["PLAYER_NAME"]
    ): row["p_make"]
    
    for _, row in lookup_table.iterrows()
}

In [44]:
global_mean = y_train.mean()

def lookup_predict(X):

    probs = []

    for _, row in X.iterrows():

        key = (
            row["MAIN_ACTION_TYPE"],
            row["PLAYER_NAME"]
        )

        # fallback to global mean if unseen
        p = lookup_dict.get(key, global_mean)

        probs.append(p)

    probs = np.array(probs)

    preds = (probs >= 0.5).astype(int)

    return preds, probs

In [45]:
y_pred_lookup, y_proba_lookup = lookup_predict(X_test)

from sklearn.metrics import (
    roc_auc_score,
    classification_report
)

print(
    "ROC-AUC:",
    roc_auc_score(y_test, y_proba_lookup)
)

print(
    classification_report(
        y_test,
        y_pred_lookup
    )
)

print("Brier score: ", brier_score_loss(y_test, y_proba_lookup))

ROC-AUC: 0.6209452563750335
              precision    recall  f1-score   support

           0       0.61      0.80      0.69      7154
           1       0.61      0.38      0.47      5795

    accuracy                           0.61     12949
   macro avg       0.61      0.59      0.58     12949
weighted avg       0.61      0.61      0.59     12949

Brier score:  0.2354969990430738