In [11]:
import sys
import os
sys.path.append(os.path.abspath("../.."))

from app.data_providers import test_train_dataset
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import TargetEncoder
from sklearn.preprocessing import FunctionTransformer

from sklearn.calibration import CalibrationDisplay

from sklearn.pipeline import FeatureUnion
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer, make_column_transformer

from sklearn.metrics import roc_auc_score, f1_score
from sklearn.metrics import classification_report

from imblearn.over_sampling import RandomOverSampler

from xgboost import XGBClassifier

import joblib

from copy import deepcopy

import shap

pd.set_option('display.max_columns', None)

In [12]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score,
    log_loss,
    brier_score_loss
)

import tensorflow as tf
from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout,
    BatchNormalization,
    Embedding,
    Flatten,
    Concatenate
)
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

In [13]:
data_train = pd.read_parquet(r"../../data/trajectory_tests/train_new_all_players_v2.parquet")
data_train.set_index('Unnamed: 0', inplace=True)
data_train = data_train.rename_axis(index=None, axis=1)

data_test = pd.read_parquet(r"../../data/trajectory_tests/test_new_all_players_v2.parquet")
data_test.set_index('Unnamed: 0', inplace=True)
data_test = data_test.rename_axis(index=None, axis=1)

In [14]:
data_train.shape

(44416, 303)

In [15]:
data_test.shape

(13112, 303)

In [16]:
data_train.head()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,ball_height,defender_closing_speed,ball_speed,ball_xy_speed,ACTION_TYPE,EVENTTIME,EVENT_TYPE,GAME_DATE,GAME_EVENT_ID,GAME_ID,GRID_TYPE,HTM,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,SHOT_TYPE,SHOT_ZONE_AREA,SHOT_ZONE_BASIC,SHOT_ZONE_RANGE,TEAM_ID,TEAM_NAME,VTM,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_WCTIMESTRING,event_PCTIMESTRING,event_HOMEDESCRIPTION,event_NEUTRALDESCRIPTION,event_VISITORDESCRIPTION,event_SCORE,event_SCOREMARGIN,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_NAME,event_PLAYER1_TEAM_ID,event_PLAYER1_TEAM_CITY,event_PLAYER1_TEAM_NICKNAME,event_PLAYER1_TEAM_ABBREVIATION,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_NAME,event_PLAYER2_TEAM_ID,event_PLAYER2_TEAM_CITY,event_PLAYER2_TEAM_NICKNAME,event_PLAYER2_TEAM_ABBREVIATION,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_NAME,event_PLAYER3_TEAM_ID,event_PLAYER3_TEAM_CITY,event_PLAYER3_TEAM_NICKNAME,event_PLAYER3_TEAM_ABBREVIATION,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,shooter_speed,nearest_teammate_distance,defenders_between,has_screen,offensive_spacing,teammate_between_defender,players_in_paint,match_key
20359,1.0,65.08406,34.87494,1.610613e+09,-22.226422,26.105691,3.049008,17.762162,0.0,1.0,1.0,668.719912,7.96082,0.541210,19.570000,18.488006,Pullup Jump shot,590,Missed Shot,20151028,152,21500010,Shot Chart Detail,HOU,98.7646,245.8234,9,2,1891,Jason Terry,2.0,50,1,25,0,592.89,3PT Field Goal,Center(C),Above the Break 3,24+ ft.,1610612745,Houston Rockets,DEN,592.89,592.89,21500010,152,2,79,2,8:45 PM,9:50,MISS Terry 26' 3PT Pullup Jump Shot,NaN,NaN,NaN,NaN,4.0,1891,Jason Terry,1.610613e+09,Houston,Rockets,HOU,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,64.66766,34.87646,7.96082,1.610613e+09,1891.0,65.08406,34.87494,1.610613e+09,2772.0,79.61659,46.98820,1.610613e+09,201951.0,72.80519,3.72471,1.610613e+09,203093.0,86.27852,38.56978,1.610613e+09,1626149.0,88.95126,12.40485,1.610613e+09,2749.0,67.72247,33.34679,1.610613e+09,200751.0,76.49703,11.88322,1.610613e+09,201589.0,87.51360,19.35221,1.610613e+09,203115.0,86.46986,35.43993,1.610613e+09,1626144.0,75.82816,38.75396,65.08406,34.87494,2.63841,-1.52815,3.049008,10.74410,3.87902,11.422893,21.38580,0.56499,21.393262,11.41297,-22.99172,25.668562,22.42954,-15.52273,27.277086,14.53253,12.11326,18.918919,21.19446,3.69484,21.514111,7.72113,-31.15023,32.092876,23.86720,-22.47009,32.780302,65.08406,34.87494,2.63841,-1.52815,3.049008,10.74410,3.87902,11.422893,21.38580,0.56499,21.393262,11.41297,-22.99172,25.668562,22.42954,-15.52273,27.277086,14.53253,12.11326,18.918919,21.19446,3.69484,21.514111,7.72113,-31.15023,32.092876,23.86720,-22.47009,32.780302,65.08406,34.87494,2.63841,-1.52815,3.049008,10.74410,3.87902,11.422893,21.38580,0.56499,21.393262,11.41297,-22.99172,25.668562,22.42954,-15.52273,27.277086,14.53253,12.11326,18.918919,21.19446,3.69484,21.514111,7.72113,-31.15023,32.092876,23.86720,-22.47009,32.780302,65.08406,34.87494,2.63841,-1.52815,3.049008,10.74410,3.87902,11.422893,21.38580,0.56499,21.393262,11.41297,-22.99172,25.668562,22.42954,-15.52273,27.277086,14.53253,12.11326,18.918919,21.19446,3.69484,21.514111,7.72113,-31.15023,32.092876,23.86720,-22.47009,32.780302,65.08406,34.87494,2.63841,-1.52815,3.049008,10.74410,3.87902,11.422893,21.38580,0.56499,21.393262,11.41297,-22.99172,25.668562,22.42954,-15.52273,27.277086,14.53253,12.11326,18.918919,21.19446,3.69484,21.514111,7.72113,-31.15023,32.092876,23.86720,-22.47009,32.780302,65.08406,34.87494,2.63841,-1.52815,3.049008,10.74410,3.87902,11.422893,21.38580,0.56499,21.393262,11.41297,-22.99172,25.668562,22.42954,-15.52273,27.277086,14.53253,12.11326,18.918919,21.19446,3.69484,21.514111,7.72113,-31.15023,32.092876,23.86720,-22.47009,32.780302,0.795364,18.918919,1,0,27.765080,0,1,21500010_
20360,7.0,89.54703,26.38937,1.610613e+09,-102.067464,1.420766,2.955751,17.486454,1.0,1.0,1.0,69.693956,6.26099,1.819132,12.484878,9.130330,Jump Shot,677,Missed Shot,20151028,6,21500010,Shot Chart Detail,HOU,-157.3231,-7.8993,11,1,201568,Danilo Gallinari,1.0,17,1,21,0,696.13,2PT Field Goal,Left Side(L),Mid-Range,16-24 ft.,1610612743,Denver Nuggets,DEN,696.13,696.13,21500010,6,2,1,1,8:15 PM,11:17,NaN,NaN,MISS Gallinari 21' Jump Shot,NaN,NaN,5.0,201568,Danilo Gallinari,1.610613e+09,Denver,Nuggets,DEN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,90.03993,9.26769,6.26099,1.610613e+09,2772.0,90.06645,9.09462,1.610613e+09,201951.0,90.78241,29.07457,1.610613e+09,201935.0,64.06776,4.14518,1.610613e+09,203093.0,63.66532,26.30262,1.610613e+09,203991.0,82.20172,27.74351,1.610613e+09,202702.0,87.67729,24.34954,1.610613e+09,201568.0,89.54703,26.38937,1.610613e+09,203914.0,77.35127,10.02182,1.610613e+09,203530.0,87.96004,17.43647,1.610613e+09,1626144.0,89.96288,31.55363,89.54703,26.38937,1.23538,2.68520,2.955751,-7.34531,1.35414,7.469088,0.51942,-17.29475,17.302548,-25.88171,-0.08675,25.881855,-25.47927,-22.24419,33.823027,-1.86974,-2.03983,2.767098,0.41585,5.16426,5.180976,-1.58699,-8.95290,9.092467,-12.19576,-16.36755,20.411596,89.54703,26.38937,1.23538,2.68520,2.955751,-7.34531,1.35414,7.469088,0.51942,-17.29475,17.302548,-25.88171,-0.08675,25.881855,-25.47927,-22.24419,33.823027,-1.86974,-2.03983,2.767098,0.41585,5.16426,5.180976,-1.58699,-8.95290,9.092467,-12.19576,-16.36755,20.411596,89.54703,26.38937,1.23538,2.68520,2.955751,-7.34531,1.35414,7.469088,0.51942,-17.29475,17.302548,-25.88171,-0.08675,25.881855,-25.47927,-22.24419,33.823027,-1.86974,-2.03983,2.767098,0.41585,5.16426,5.180976,-1.58699,-8.95290,9.092467,-12.19576,-16.36755,20.411596,89.54703,26.38937,1.23538,2.68520,2.955751,-7.34531,1.35414,7.469088,0.51942,-17.29475,17.302548,-25.88171,-0.08675,25.881855,-25.47927,-22.24419,33.823027,-1.86974,-2.03983,2.767098,0.41585,5.16426,5.180976,-1.58699,-8.95290,9.092467,-12.19576,-16.36755,20.411596,89.54703,26.38937,1.23538,2.68520,2.955751,-7.34531,1.35414,7.469088,0.51942,-17.29475,17.302548,-25.88171,-0.08675,25.881855,-25.47927,-22.24419,33.823027,-1.86974,-2.03983,2.767098,0.41585,5.16426,5.180976,-1.58699,-8.95290,9.092467,-12.19576,-16.36755,20.411596,89.54703,26.38937,1.23538,2.68520,2.955751,-7.34531,1.35414,7.469088,0.51942,-17.29475,17.302548,-25.88171,-0.08675,25.881855,-25.47927,-22.24419,33.823027,-1.86974,-2.03983,2.767098,0.41585,5.16426,5.180976,-1.58699,-8.95290,9.092467,-12.19576,-16.36755,20.411596,1.865342,2.767098,0,0,12.174492,0,6,21500010_
20361,7.0,83.74466,27.25147,1.610613e+09,-22.242653,5.947931,1.056887,14.683222,1.0,1.0,1.0,135.612276,4.10760,1.008438,9.133470,5.100976,Cutting Dunk Shot,572,Made Shot,20151028,22,21500010,Shot Chart Detail,HOU,-64.8797,25.3860,9,1,201568,Danilo Gallinari,1.0,32,1,0,1,587.44,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612743,Denver Nuggets,DEN,587.44,587.44,21500010,22,1,108,1,8:17 PM,9:32,NaN,NaN,Gallinari Cutting Dunk Shot (2 PTS) (Lauvergn...,6 - 0,-6.0,5.0,201568,Danilo Gallinari,1.610613e+09,Denver,Nuggets,DEN,5,203530,Joffrey Lauvergne,1.610613e+09,Denver,Nuggets,DEN,0,0,NaN,NaN,NaN,NaN,NaN,86.71140,18.51203,4.10760,1.610613e+09,2772.0,83.30459,28.21238,1.610613e+09,201951.0,71.33016,43.72356,1.610613e+09,201935.0,52.08917,22.43490,1.610613e+09,203093.0,85.52202,19.66621,1.610613e+09,203991.0,88.16197,38.32520,1.610613e+09,202702.0,85.83927,21.49771,1.610613e+09,201568.0,83.74466,27.25147,1.610613e+09,203914.0,68.93466,22.00416,1.610613e+09,203530.0,88.68085,33.49255,1.610613e+09,1626144.0,80.99875,32.41702,83.74466,27.25147,-0.44007,0.96091,1.056887,1.77736,-7.58526,7.790711,4.41731,11.07373,11.922253,-12.41450,16.47209,20.626429,-31.65549,-4.81657,32.019828,-2.74591,5.16555,5.850037,2.09461,-5.75376,6.123165,4.93619,6.24108,7.957201,-14.81000,-5.24731,15.712109,83.74466,27.25147,-0.44007,0.96091,1.056887,1.77736,-7.58526,7.790711,4.41731,11.07373,11.922253,-12.41450,16.47209,20.626429,-31.65549,-4.81657,32.019828,-2.74591,5.16555,5.850037,2.09461,-5.75376,6.123165,4.93619,6.24108,7.957201,-14.81000,-5.24731,15.712109,83.74466,27.25147,-0.44007,0.96091,1.056887,1.77736,-7.58526,7.790711,4.41731,11.07373,11.922253,-12.41450,16.47209,20.626429,-31.65549,-4.81657,32.019828,-2.74591,5.16555,5.850037,2.09461,-5.75376,6.123165,4.93619,6.24108,7.957201,-14.81000,-5.24731,15.712109,83.74466,27.25147,-0.44007,0.96091,1.056887,1.77736,-7.58526,7.790711,4.41731,11.07373,11.922253,-12.41450,16.47209,20.626429,-31.65549,-4.81657,32.019828,-2.74591,5.16555,5.850037,2.09461,-5.75376,6.123165,4.93619,6.24108,7.957201,-14.81000,-5.24731,15.712109,83.74466,27.25147,-0.44007,0.96091,1.056887,1.77736,-7.58526,7.790711,4.41731,11.07373,11.922253,-12.41450,16.47209,20.626429,-31.65549,-4.81657,32.019828,-2.74591,5.16555,5.850037,2.09461,-5.75376,6.123165,4.93619,6.24108,7.957201,-14.81000,-5.24731,15.712109,83.74466,27.25147,-0.44007,0.96091,1.056887,1.77736,-7.58526,7.790711,4.41731,11.07373,11.922253,-12.41450,16.47209,20.626429,-31.65549,-4.81657,32.019828,-2.74591,5.16555,5.850037,2.09461,-5.75376,6.123165,4.93619,6.24108,7.957201,-14.81000,-5.24731,15.712109,5.547458,5.850037,0,0,12.336414,0,5,21500010_
20362,7.0,64.51776,27.91574,1.610613e+09,-6.723694,24.903519,4.694814,16.264428,0.0,1.0,1.0,452.455871,8.18084,0.762027,19.525365,18.425577,Jump Shot,539,Missed Shot,20151028,29,21500010,Shot Chart Detail,HOU,31.9245,242.3769,8,1,201568,Danilo Gallinari,1.0,59,1,22,0,542.07,2PT Field Goal,Center(C),Mid-Range,16-24 ft.,1610612743,Denver Nuggets,DEN,542.07,542.07,21500010,29,2,1,1,8:19 PM,8:59,NaN,NaN,MISS Gallinari 23' Jump Shot,NaN,NaN,5.0,201568,Danilo Gallinari,1.610613e+09,Denver,Nuggets,DEN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,65.01231,28.19245,8.18084,1.610613e+09,2772.0,75.04841,16.93641,1.610613e+09,201951.0,67.88466,31.18763,1.610613e+09,201935.0,85.64071,9.87995,1.610613e+09,203093.0,86.58799,33.65900,1.610613e+09,203991.0,75.07314,25.47643,1.610613e+09,202702.0,91.72319,21.71308,1.610613e+09,201568.0,64.51776,27.91574,1.610613e+09,203914.0,90.15150,31.11133,1.610613e+09,203530.0,80.35734,16.65440,1.610613e+09,1626144.0,76.48768,46.99629,64.51776,27.91574,3.36690,3.27189,4.694814,10.55538,-2.43931,10.833572,10.53065,-10.97933,15.213161,22.07023,5.74326,22.805264,21.12295,-18.03579,27.775326,15.83958,-11.26134,19.434765,11.96992,19.08055,22.524351,25.63374,3.19559,25.832159,27.20543,-6.20266,27.903556,64.51776,27.91574,3.36690,3.27189,4.694814,10.55538,-2.43931,10.833572,10.53065,-10.97933,15.213161,22.07023,5.74326,22.805264,21.12295,-18.03579,27.775326,15.83958,-11.26134,19.434765,11.96992,19.08055,22.524351,25.63374,3.19559,25.832159,27.20543,-6.20266,27.903556,64.51776,27.91574,3.36690,3.27189,4.694814,10.55538,-2.43931,10.833572,10.53065,-10.97933,15.213161,22.07023,5.74326,22.805264,21.12295,-18.03579,27.775326,15.83958,-11.26134,19.434765,11.96992,19.08055,22.524351,25.63374,3.19559,25.832159,27.20543,-6.20266,27.903556,64.51776,27.91574,3.36690,3.27189,4.694814,10.55538,-2.43931,10.833572,10.53065,-10.97933,15.213161,22.07023,5.74326,22.805264,21.12295,-18.03579,27.775326,15.83958,-11.26134,19.434765,11.96992,19.08055,22.524351,25.63374,3.19559,25.832159,27.20543,-6.20266,27.903556,64.51776,27.91574,3.36690,3.27189,4.694814,10.55538,-2.43931,10.833572,10.53065,-10.97933,15.213161,22.07023,5.74326,22.805264,21.12295,-18.03579,27.775326,15.83958,-11.26134,19.434765,11.96992,19.08055,22.524351,25.63374,3.19559,25.832159,27.20543,-6.20266,27.903556,64.51776,27.91574,3.36690,3.27189,4.694814,10.55538,-2.43931,10.833572,10.53065,-10.97933,15.213161,22.07023,5.74326,22.805264,21.12295,-18.03579,27.775326,15.83958,-11.26134,19.434765,11.96992,19.08055,22.524351,25.63374,3.19559,25.832159,27.20543,-6.20266,27.903556,3.358074,19.434765,1,0,21.618614,0,3,21500010_
20363,9.0,77.38215,21.91623,1.610613e+09,14.565755,12.261953,2.438755,14.367961,1.0,2.0,2.0,416.788380,5.63364,-0.902426,18.290018,15.135546,Layup Shot,138,Missed Shot,20151028,113,21500010,Shot Chart Detail,HOU,158.7235,203.7542,2,1,201568,Danilo Gallinari,1.0,18,1,1,0,143.70,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612743,Denver Nuggets,DEN,143.70,143.70,21500010,113,2,5,1,8:34 PM,2:18,NaN,NaN,MISS Gallinari 1' Layup,NaN,NaN,5.0,201568,Danilo Gallinari,1.610613e+09,Denver,Nuggets,DEN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,68.87458,40.87235,5.63364,1.610613e+09,201147.0,47.88493,18.30748,1.610613e+09,201951.0,75.62982,25.32122,1.610613e+09,201976.0,76.40971,19.67974,1.610613e+09,201935.0,80.26172,36.85204,1.610613e+09,1626149.0,62.07244,35.76436,1.610613e+09,2749.0,68.57378,41.75807,1.610613e+09,200751.0,62.18649,7.91741,1.610613e+09,201589.0,73.19932,26.59086,1.610613e+09,201568.0,77.38215,21.91623,1.610613e+09,203115.0,86.96109,46.74447,77.38215,21.91623,-0.97244,-2.23649,2.438755,-1.75233,3.40499,3.829441,2.87957,14.93581,15.210863,-15.30971,13.84813,20.643593,-29.49722,-3.60875,29.717151,-4.18283,4.67463,6.272817,-15.19566,-13.99882,20.660955,-8.80837,19.84184,21.709122,9.57894,24.82824,26.611982,77.38215,21.91623,-0.97244,-2.23649,2.438755,-1.75233,3.40499,3.829441,2.87957,14.93581,15.210863,-15.30971,13.84813,20.643593,-29.49722,-3.60875,29.717151,-4.18283,4.67463,6.272817,-15.19566,-13.99882,20.660955,-8.80837,19.84184,21.709122,9.57894,24.82824,26.611982,77.38215,21.91623,-0.97244,-2.23649,2.438755,-1.75233,3.40499,3.829441,2.87957,14.93581,15.210863,-15.30971,13.84813,20.643593,-29.49722,-3.60875,29.717151,-4.18283,4.67463,6.272817,-15.19566,-13.99882,20.660955,-8.80837,19.84184,21.709122,9.57894,24.82824,26.611982,77.38215,21.91623,-0.97244,-2.23649,2.438755,-1.75233,3.40499,3.829441,2.87957,14.93581,15.210863,-15.30971,13.84813,20.643593,-29.49722,-3.60875,29.717151,-4.18283,4.67463,6.272817,-15.19566,-13.99882,20.660955,-8.80837,19.84184,21.709122,9.57894,24.82824,26.611982,77.38215,21.91623,-0.97244,-2.23649,2.438755,-1.75233,3.40499,3.829441,2.87957,14.93581,15.210863,-15.30971,13.84813,20.643593,-29.49722,-3.60875,29.717151,-4.18283,4.67463,6.272817,-15.19566,-13.99882,20.660955,-8.80837,19.84184,21.709122,9.57894,24.82824,26.611982,77.38215,21.91623,-0.97244,-2.23649,2.438755,-1.75233,3.40499,3.829441,2.87957,14.93581,15.210863,-15.30971,13.84813,20.643593,-29.49722,-3.60875,29.717151,-4.18283,4.67463,6.272817,-15.19566,-13.99882,20.660955,-8.80837,19.84184,21.709122,9.57894,24.82824,26.611982,8.071871,6.272817,0,0,23.674216,0,3,21500010_

In [17]:
# ============================================================
# TARGET
# ============================================================

TARGET = "SHOT_MADE_FLAG"  


# ============================================================
# FEATURE GROUPS
# ============================================================

tracking_features = [
    # t0
    "shooter_x_t0", "shooter_y_t0",
    "defender1_dx_t0", "defender1_dy_t0", "defender1_dist_t0",
    "defender2_dx_t0", "defender2_dy_t0", "defender2_dist_t0",
    "defender3_dx_t0", "defender3_dy_t0", "defender3_dist_t0",
    "defender4_dx_t0", "defender4_dy_t0", "defender4_dist_t0",
    "defender5_dx_t0", "defender5_dy_t0", "defender5_dist_t0",
    "attacker1_dx_t0", "attacker1_dy_t0", "attacker1_dist_t0",
    "attacker2_dx_t0", "attacker2_dy_t0", "attacker2_dist_t0",
    "attacker3_dx_t0", "attacker3_dy_t0", "attacker3_dist_t0",
    "attacker4_dx_t0", "attacker4_dy_t0", "attacker4_dist_t0",

    # t1
    "shooter_x_t1", "shooter_y_t1",
    "defender1_dx_t1", "defender1_dy_t1", "defender1_dist_t1",
    "defender2_dx_t1", "defender2_dy_t1", "defender2_dist_t1",
    "defender3_dx_t1", "defender3_dy_t1", "defender3_dist_t1",
    "defender4_dx_t1", "defender4_dy_t1", "defender4_dist_t1",
    "defender5_dx_t1", "defender5_dy_t1", "defender5_dist_t1",
    "attacker1_dx_t1", "attacker1_dy_t1", "attacker1_dist_t1",
    "attacker2_dx_t1", "attacker2_dy_t1", "attacker2_dist_t1",
    "attacker3_dx_t1", "attacker3_dy_t1", "attacker3_dist_t1",
    "attacker4_dx_t1", "attacker4_dy_t1", "attacker4_dist_t1",

    # t2
    "shooter_x_t2", "shooter_y_t2",
    "defender1_dx_t2", "defender1_dy_t2", "defender1_dist_t2",
    "defender2_dx_t2", "defender2_dy_t2", "defender2_dist_t2",
    "defender3_dx_t2", "defender3_dy_t2", "defender3_dist_t2",
    "defender4_dx_t2", "defender4_dy_t2", "defender4_dist_t2",
    "defender5_dx_t2", "defender5_dy_t2", "defender5_dist_t2",
    "attacker1_dx_t2", "attacker1_dy_t2", "attacker1_dist_t2",
    "attacker2_dx_t2", "attacker2_dy_t2", "attacker2_dist_t2",
    "attacker3_dx_t2", "attacker3_dy_t2", "attacker3_dist_t2",
    "attacker4_dx_t2", "attacker4_dy_t2", "attacker4_dist_t2",

    # t3
    "shooter_x_t3", "shooter_y_t3",
    "defender1_dx_t3", "defender1_dy_t3", "defender1_dist_t3",
    "defender2_dx_t3", "defender2_dy_t3", "defender2_dist_t3",
    "defender3_dx_t3", "defender3_dy_t3", "defender3_dist_t3",
    "defender4_dx_t3", "defender4_dy_t3", "defender4_dist_t3",
    "defender5_dx_t3", "defender5_dy_t3", "defender5_dist_t3",
    "attacker1_dx_t3", "attacker1_dy_t3", "attacker1_dist_t3",
    "attacker2_dx_t3", "attacker2_dy_t3", "attacker2_dist_t3",
    "attacker3_dx_t3", "attacker3_dy_t3", "attacker3_dist_t3",
    "attacker4_dx_t3", "attacker4_dy_t3", "attacker4_dist_t3",

    # t4
    "shooter_x_t4", "shooter_y_t4",
    "defender1_dx_t4", "defender1_dy_t4", "defender1_dist_t4",
    "defender2_dx_t4", "defender2_dy_t4", "defender2_dist_t4",
    "defender3_dx_t4", "defender3_dy_t4", "defender3_dist_t4",
    "defender4_dx_t4", "defender4_dy_t4", "defender4_dist_t4",
    "defender5_dx_t4", "defender5_dy_t4", "defender5_dist_t4",
    "attacker1_dx_t4", "attacker1_dy_t4", "attacker1_dist_t4",
    "attacker2_dx_t4", "attacker2_dy_t4", "attacker2_dist_t4",
    "attacker3_dx_t4", "attacker3_dy_t4", "attacker3_dist_t4",
    "attacker4_dx_t4", "attacker4_dy_t4", "attacker4_dist_t4",

    # t5
    "shooter_x_t5", "shooter_y_t5",
    "defender1_dx_t5", "defender1_dy_t5", "defender1_dist_t5",
    "defender2_dx_t5", "defender2_dy_t5", "defender2_dist_t5",
    "defender3_dx_t5", "defender3_dy_t5", "defender3_dist_t5",
    "defender4_dx_t5", "defender4_dy_t5", "defender4_dist_t5",
    "defender5_dx_t5", "defender5_dy_t5", "defender5_dist_t5",
    "attacker1_dx_t5", "attacker1_dy_t5", "attacker1_dist_t5",
    "attacker2_dx_t5", "attacker2_dy_t5", "attacker2_dist_t5",
    "attacker3_dx_t5", "attacker3_dy_t5", "attacker3_dist_t5",
    "attacker4_dx_t5", "attacker4_dy_t5", "attacker4_dist_t5",
]

additional_features = [
    "shot_angle",
    "distance_to_basket_tracking",
    "nearest_defender_dist",
    "avg_defender_dist",
    "defenders_within_3ft",
    "defenders_within_5ft",
    "defenders_within_7ft",
    "defender_closing_speed",
    "defenders_between",
    "has_screen",
    "teammate_between_defender",
    "players_in_paint",
    "shooter_speed",
    "nearest_teammate_distance"
]

continuous_features = (
    tracking_features +
    additional_features
)

categorical_features = [
    "PERIOD"
]

player_feature = "PLAYER_ID"

In [18]:
required_columns = (
    continuous_features +
    categorical_features +
    [player_feature, TARGET]
)

data_train = data_train.dropna(subset=required_columns).copy()
data_test = data_test.dropna(subset=required_columns).copy()

In [19]:
# ============================================================
# LABEL ENCODE PLAYER IDS
# ============================================================

unique_players = data_train[player_feature].unique()

player_to_idx = {
    player_id: idx + 1
    for idx, player_id in enumerate(unique_players)
}

# 0 reserved for UNKNOWN players
UNKNOWN_PLAYER_IDX = 0


# ============================================================
# ENCODE TRAIN
# ============================================================

data_train[player_feature] = (
    data_train[player_feature]
    .map(player_to_idx)
    .fillna(UNKNOWN_PLAYER_IDX)
    .astype(int)
)


# ============================================================
# ENCODE TEST
# ============================================================

data_test[player_feature] = (
    data_test[player_feature]
    .map(player_to_idx)
    .fillna(UNKNOWN_PLAYER_IDX)
    .astype(int)
)


# ============================================================
# NUMBER OF PLAYERS
# ============================================================

num_players = max(player_to_idx.values()) + 1


# ============================================================
# TRAIN / VALIDATION / TEST SPLIT
# ============================================================

X_train = data_train.drop('SHOT_MADE_FLAG', axis=1)
y_train = data_train['SHOT_MADE_FLAG']

X_test = data_test.drop('SHOT_MADE_FLAG', axis=1)
y_test = data_test['SHOT_MADE_FLAG']

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=42)

In [20]:
# ============================================================
# CONTINUOUS FEATURES
# ============================================================

X_train_cont = X_train[continuous_features].values
X_valid_cont = X_val[continuous_features].values
X_test_cont = X_test[continuous_features].values


# ============================================================
# STANDARDIZATION
# ============================================================

scaler = StandardScaler()

X_train_cont = scaler.fit_transform(X_train_cont)
X_valid_cont = scaler.transform(X_valid_cont)
X_test_cont = scaler.transform(X_test_cont)


# ============================================================
# PERIOD INPUT
# ============================================================

X_train_period = X_train["PERIOD"].values
X_valid_period = X_val["PERIOD"].values
X_test_period = X_test["PERIOD"].values


# ============================================================
# PLAYER INPUT
# ============================================================

X_train_player = X_train[player_feature].values
X_valid_player = X_val[player_feature].values
X_test_player = X_test[player_feature].values


# ============================================================
# TARGET
# ============================================================

y_train = y_train.values
y_valid = y_val.values
y_test = y_test.values

In [21]:
# ============================================================
# MODEL
# ============================================================

# --------------------------------
# Continuous Input
# --------------------------------

continuous_input = Input(
    shape=(len(continuous_features),),
    name="continuous_input"
)

x = Dense(512, activation="relu")(continuous_input)
x = BatchNormalization()(x)
x = Dropout(0.30)(x)

x = Dense(256, activation="relu")(x)
x = BatchNormalization()(x)
x = Dropout(0.25)(x)

x = Dense(128, activation="relu")(x)
x = BatchNormalization()(x)


# --------------------------------
# PLAYER EMBEDDING
# --------------------------------

player_input = Input(
    shape=(1,),
    name="player_input"
)

player_embedding = Embedding(
    input_dim=num_players + 1,
    output_dim=16,
    name="player_embedding"
)(player_input)

player_embedding = Flatten()(player_embedding)


# --------------------------------
# PERIOD EMBEDDING
# --------------------------------

period_input = Input(
    shape=(1,),
    name="period_input"
)

period_embedding = Embedding(
    input_dim=10,
    output_dim=4,
    name="period_embedding"
)(period_input)

period_embedding = Flatten()(period_embedding)


# --------------------------------
# CONCATENATE
# --------------------------------

x = Concatenate()([
    x,
    player_embedding,
    period_embedding
])

x = Dense(64, activation="relu")(x)
x = Dropout(0.20)(x)

output = Dense(
    1,
    activation="sigmoid"
)(x)


# ============================================================
# BUILD MODEL
# ============================================================

model = Model(
    inputs=[
        continuous_input,
        player_input,
        period_input
    ],
    outputs=output
)

model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.AUC(name="auc")
    ]
)

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ continuous_input (InputLayer) │ (None, 188)               │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense (Dense)                 │ (None, 512)               │          96,768 │ continuous_input[0][0]     │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ batch_normalization           │ (None, 512)               │           2,048 │ dense[0][0]                │
│ (BatchNormalization)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout (Dropout)             │ (None, 512)               │               0 │ batch_normalization[0][0]  │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_1 (Dense)               │ (None, 256)               │         131,328 │ dropout[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ batch_normalization_1         │ (None, 256)               │           1,024 │ dense_1[0][0]              │
│ (BatchNormalization)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout_1 (Dropout)           │ (None, 256)               │               0 │ batch_normalization_1[0][… │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ player_input (InputLayer)     │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ period_input (InputLayer)     │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_2 (Dense)               │ (None, 128)               │          32,896 │ dropout_1[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ player_embedding (Embedding)  │ (None, 1, 16)             │           6,640 │ player_input[0][0]         │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ period_embedding (Embedding)  │ (None, 1, 4)              │              40 │ period_input[0][0]         │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ batch_normalization_2         │ (None, 128)               │             512 │ dense_2[0][0]              │
│ (BatchNormalization)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten (Flatten)             │ (None, 16)                │               0 │ player_embedding[0][0]     │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten_1 (Flatten)           │ (None, 4)                 │               0 │ period_embedding[0][0]     │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ concatenate (Concatenate)     │ (None, 148)               │               0 │ batch_normalization_2[0][… │
│                               │                           │                 │ flatten[0][0],             │
│                               │                           │                 │ flatten_1[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_3 (Dense)               │ (None, 64)                │           9,536 │ concatenate[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout_2 (Dropout)           │ (None, 64)                │               0 │ dense_3[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_4 (Dense)               │ (None, 1)                 │              65 │ dropout_2[0][0]            │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 280,857 (1.07 MB)

 Trainable params: 279,065 (1.06 MB)

 Non-trainable params: 1,792 (7.00 KB)

In [22]:
# ============================================================
# EARLY STOPPING
# ============================================================

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

In [23]:
# ============================================================
# TRAIN
# ============================================================

history = model.fit(
    x=[
        X_train_cont,
        X_train_player,
        X_train_period
    ],
    y=y_train,

    validation_data=(
        [
            X_valid_cont,
            X_valid_player,
            X_valid_period
        ],
        y_valid
    ),

    epochs=100,
    batch_size=256,
    callbacks=[early_stopping],
    verbose=1
)

Epoch 1/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 6s 19ms/step - auc: 0.5352 - loss: 0.7162 - val_auc: 0.5594 - val_loss: 0.6886
Epoch 2/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - auc: 0.5559 - loss: 0.6908 - val_auc: 0.5743 - val_loss: 0.6846
Epoch 3/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - auc: 0.5718 - loss: 0.6830 - val_auc: 0.5728 - val_loss: 0.6859
Epoch 4/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - auc: 0.5898 - loss: 0.6767 - val_auc: 0.5793 - val_loss: 0.6818
Epoch 5/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - auc: 0.5995 - loss: 0.6730 - val_auc: 0.5727 - val_loss: 0.6835
Epoch 6/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - auc: 0.6045 - loss: 0.6713 - val_auc: 0.5771 - val_loss: 0.6843
Epoch 7/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - auc: 0.6087 - loss: 0.6695 - val_auc: 0.5761 - val_loss: 0.6828
Epoch 8/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - auc: 0.6139 - loss: 0.6681 - val_auc: 0.5711 - val_loss: 0.6845
Epoch 9/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - auc: 0.6142 - loss: 0.6674 - val_auc: 0.5780 - val_loss: 0.6844
Epoch 10/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - auc: 0.6223 - loss: 0.6642 - val_auc: 0.5780 - val_loss: 0.6848
Epoch 11/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - auc: 0.6216 - loss: 0.6641 - val_auc: 0.5732 - val_loss: 0.6869
Epoch 12/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - auc: 0.6231 - loss: 0.6638 - val_auc: 0.5745 - val_loss: 0.6854
Epoch 13/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - auc: 0.6274 - loss: 0.6613 - val_auc: 0.5721 - val_loss: 0.6889
Epoch 14/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - auc: 0.6313 - loss: 0.6602 - val_auc: 0.5715 - val_loss: 0.6885

In [24]:
# ============================================================
# PREDICTIONS
# ============================================================

y_pred_proba = model.predict([
    X_test_cont,
    X_test_player,
    X_test_period
]).flatten()

y_pred = (y_pred_proba >= 0.5).astype(int)


# ============================================================
# EVALUATION
# ============================================================

auc = roc_auc_score(y_test, y_pred_proba)
ll = log_loss(y_test, y_pred_proba)
brier = brier_score_loss(y_test, y_pred_proba)

print("\n====================")
print(f"AUC:        {auc:.4f}")
print(f"Log Loss:   {ll:.4f}")
print(f"Brier:      {brier:.4f}")
print("====================")

410/410 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

====================
AUC:        0.5831
Log Loss:   0.6773
Brier:      0.2422
====================

In [26]:
display(pd.crosstab(y_test, y_pred))
print(classification_report(y_test, y_pred))

col_0     0     1
row_0
0      5440  1809
1      3794  2069

              precision    recall  f1-score   support

           0       0.59      0.75      0.66      7249
           1       0.53      0.35      0.42      5863

    accuracy                           0.57     13112
   macro avg       0.56      0.55      0.54     13112
weighted avg       0.56      0.57      0.55     13112

In [30]:
# Build error Dataframe

error_df = X_test.copy()

error_df["y_true"] = y_test
error_df["y_pred"] = y_pred
error_df["y_pred_proba"] = y_pred_proba

# confidence
error_df["confidence"] = np.where(
    error_df["y_pred"] == 1,
    error_df["y_pred_proba"],
    1 - error_df["y_pred_proba"]
)

error_df["correct"] = (
    error_df["y_true"] == error_df["y_pred"]
)

# prediction error magnitude
error_df["error"] = abs(error_df["y_true"] - error_df["y_pred_proba"])

In [32]:
for action_type in error_df["ACTION_TYPE"].value_counts().index[:15]:

    subset = error_df[
        error_df["ACTION_TYPE"] == action_type
    ]

    accuracy = (
        subset["y_true"] == subset["y_pred"]
    ).mean()

    print("\n" + "="*60)
    print(f"{action_type}")
    print(f"n = {len(subset)}")
    print(f"accuracy = {accuracy:.3f}")
    print(f"roc-auc = {roc_auc_score(subset["y_true"], subset["y_pred_proba"]):.3f}")
    print("="*60)

    cm = pd.crosstab(
        subset["y_true"],
        subset["y_pred"],
        rownames=["Actual"],
        colnames=["Predicted"]
    )

    display(cm)

============================================================
Jump Shot
n = 6406
accuracy = 0.612
roc-auc = 0.502
============================================================

Predicted     0    1
Actual
0          3571  797
1          1686  352

============================================================
Layup Shot
n = 1286
accuracy = 0.568
roc-auc = 0.578
============================================================

Predicted    0    1
Actual
0          460  298
1          258  270

============================================================
Driving Layup Shot
n = 796
accuracy = 0.515
roc-auc = 0.553
============================================================

Predicted    0    1
Actual
0          201  102
1          284  209

============================================================
Pullup Jump shot
n = 627
accuracy = 0.435
roc-auc = 0.479
============================================================

Predicted    0   1
Actual
0          215  60
1          294  58

============================================================
Floating Jump shot
n = 346
accuracy = 0.520
roc-auc = 0.555
============================================================

Predicted    0   1
Actual
0          121  61
1          105  59

============================================================
Hook Shot
n = 311
accuracy = 0.511
roc-auc = 0.519
============================================================

Predicted   0   1
Actual
0          68  79
1          73  91

============================================================
Step Back Jump shot
n = 264
accuracy = 0.519
roc-auc = 0.557
============================================================

Predicted    0   1
Actual
0          121  15
1          112  16

============================================================
Tip Layup Shot
n = 240
accuracy = 0.546
roc-auc = 0.554
============================================================

Predicted   0   1
Actual
0          66  59
1          50  65

============================================================
Turnaround Jump Shot
n = 232
accuracy = 0.565
roc-auc = 0.515
============================================================

Predicted   0   1
Actual
0          98  44
1          57  33

============================================================
Dunk Shot
n = 225
accuracy = 0.676
roc-auc = 0.649
============================================================

Predicted   0    1
Actual
0          10   14
1          59  142

============================================================
Cutting Layup Shot
n = 205
accuracy = 0.585
roc-auc = 0.660
============================================================

Predicted   0   1
Actual
0          23  15
1          70  97

============================================================
Fadeaway Jump Shot
n = 204
accuracy = 0.618
roc-auc = 0.522
============================================================

Predicted    0   1
Actual
0          102  11
1           67  24

============================================================
Running Layup Shot
n = 178
accuracy = 0.494
roc-auc = 0.529
============================================================

Predicted   0   1
Actual
0          24  23
1          67  64

============================================================
Driving Finger Roll Layup Shot
n = 142
accuracy = 0.542
roc-auc = 0.637
============================================================

Predicted   0   1
Actual
0          34  14
1          51  43

============================================================
Putback Layup Shot
n = 125
accuracy = 0.448
roc-auc = 0.491
============================================================

Predicted   0   1
Actual
0          20  16
1          53  36